### ISSUE TITLE
Markdown pour les grands textbox

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/portail#10]
Permettre l'utilisation du Markdown pour pouvoir structurer le texte des grands formulaires, notamment : Sommiers, Tuyauterie, Evènement.

**Comment by LucasBerbesson** [comment]
C'est bon normalement, par contre si on ajoute des titres ça descructure pas mal la page

**Comment by LucasBerbesson** [comment]
Comme ça ? 
<img width="1374" alt="Capture d’écran 2020-01-24 à 18 56 18" src="https://user-images.githubusercontent.com/8393585/73091679-3cfa0680-3edb-11ea-94e9-bbf8d9de55c4.png">

**Comment by LucasBerbesson** [comment]
Au fait tu n'as pas peur que l'édition des orgues devienne trop complexe ? il commence à y avoir bcp de champs je trouve :)

**Comment by GwilhermPoullennec** [comment]
Si, je pense on arrive au taquet !

**Comment by GwilhermPoullennec** [comment]
Oui !

**Comment by LucasBerbesson** [comment]
Presque bon, ajouter un offset des titres ajoutés par les utilisateurs

**Comment by LucasBerbesson** [comment]
On va plutôt mettre en place un WYSIWYG html

**Comment by GwilhermPoullennec** [comment]
Au fait, ne faudrait-il pas mixer les deux idées (WYSWYG et Markdown) ?
Sinon quand on exporte en JSON, on aura des H3, H4 sans les H1, H2.
SimpleMDE Markdown Editor ?
A discuter

**Comment by LucasBerbesson** [comment]
J'ai retiré la possibilité de mettre des titres dans les WYSIWYG. Au final on se retrouve avec une syntaxe proche du markdown et si besoin il est facile de faire la conversion html => markdown après coup.
