### ISSUE TITLE
Champ transmission notes : longueur du champt trop courte

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/portail#101]
Pour "Electrique proportionnelle" (26 au lieu de 20 max).

**Comment by LucasBerbesson** [comment]
Au fait si tu modifies une classe qui hérite de models.Model, il faut ensuite lancer la commande `python manage.py makemigrations` pour générer les fichiers de migrations (et ensuite les pousser ici sur Github). 
Là ta modif de longueur de caractère est apparue lorsque j'ai lancé la commande de mon côté : 
https://github.com/inventaire-des-orgues/portail/commit/ba4762515f18c6c4c8203d97e4b0de174af144e8

**Comment by GwilhermPoullennec** [comment]
OK, je pense que j'étais encore sur mon ancien régime, donc avec mes migrations dans le .gitignore
Merci !
