### ISSUE TITLE
Ajout d'un registre : absence bouton registre supplémentaire

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/portail#103]
Lorsque l'on complète les registres, l'interace propose trois registres vides supplémentaires. Une fois ceux-ci complétés, il faut enregistrer et revenir pour avoir encore trois nouveaux registres.
- passe le 3 à 10 registres vides
- prévoir un bouton "ajouter un registre" pour éviter de devoir quitter cette interface.

**Comment by GwilhermPoullennec** [comment]
passe le 3 à 10 registres vides : FAIT

**Comment by GwilhermPoullennec** [comment]
Proposition pour traiter le deuxième item :
chaque fois que l'on a remplit le dixième jeu, il propose de nouveau trois champs vides

**Comment by LucasBerbesson** [comment]
J'ai fini par trouver une solution simple 1d7acf4
