### ISSUE TITLE
Mini-composition dans le cartouche de résumé

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/portail#11]
Afficher l'information Clavier et Pédale de façon commune, sous le format :
[nombre de claviers en chiffres romains]["/P" si Pédale]

Exemples :
- III/P
- II

**Comment by LucasBerbesson** [comment]
ok

**Comment by LucasBerbesson** [comment]
Je fais un test unitaire et je close

**Comment by GwilhermPoullennec** [comment]
Voir aussi #34
