### ISSUE TITLE
Bouton contact

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/portail#110]
Bouton pour "ajouter un orgue" qui renvoie vers un formulaire de contact avec les informations indispensables.
A positionner sur la pages "Les orgues" entre le menu et la liste, prune sur fond blanc.

**Comment by GwilhermPoullennec** [comment]
#105

**Comment by LucasBerbesson** [comment]
C'est fait, par contre le bouton de contact ne s'affiche que lorsqu'il n'y a pas de résultat de recherche
