### ISSUE TITLE
Plantage serveur

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/portail#113]
Plantage serveur le 4/6/2020.
A cause du crontab ?
J'ai redémarré vers 18h30.

**Comment by GwilhermPoullennec** [comment]
Oui il y aussi une erreur de certificat.
Mais je ne sais pas si une erreur de certificat peut faire planter un serveur, il semblait planté. Non ?

**Comment by LucasBerbesson** [comment]
Bizarre, je n'arrive pas à voir ce qu'il s'est passé... et je ne comprends pas non plus pourquoi le certificat ne s'est pas automatiquement renouvelé
