### ISSUE TITLE
Calcul du taux d'avancement

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/portail#115]
- Juste les informations géographiques (commune, région, département) : 5%
- + un édifice qui ne soit pas que "église" : 10%
- + état de l'instrument : 20%
- + composition : 30%
- + photos : 60%
- + champs texte longs bien complétés : 100%

**Comment by LucasBerbesson** [comment]
C'est fait

**Comment by GwilhermPoullennec** [comment]
Rendre le calcul plus intelligible : résumé des rubriques soupesées.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
