### ISSUE TITLE
Ajouter le logo MH si orgue inscrit ou classé 

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/portail#122]
Sur le bandeau de droite à côté des n°PM

**Comment by GwilhermPoullennec** [comment]
https://www.culture.gouv.fr/Sites-thematiques/Monuments-historiques/Presentation/Logotypes-Monument-historique-et-Site-patrimonial-remarquable

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Lluke-h** [comment]
fb533fe Afiichage sur le bandeau du logo monument historique (version noire, on peut aussi mettre l'original en rouge)
