### ISSUE TITLE
Avoir url par codification

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/portail#126]
Les codifications sont par construction uniques.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by GwilhermPoullennec** [comment]
- en gardant url à la mode actuelle si défaut de codification en attendant, pour les nouveaux orgues, d'avoir repris le code de création d'une codification ?

**Comment by LucasBerbesson** [comment]
Tu veux remplacer les identifiants type "4139": 
https://inventaire-des-orgues.fr/detail/orgue-montebourg-eglise-saint-jacques-4139/ 
par les codifications quand elles existent ?

**Comment by GwilhermPoullennec** [comment]
oui
ou que https://inventaire-des-orgues.fr/detail/FR-50341-MTEBO-STJACQ1-X pointe vers le même endroit.
Qu'en penses-tu ?

**Comment by LucasBerbesson** [comment]
Je peux faire en sorte que les codifications redirigent vers le même endroit. Il y aura 2 façons différentes d'accéder à la fiche d'un orgue. Je pense qu'il faut garder le schéma d'URL existant pour le référencement.

**Comment by GwilhermPoullennec** [comment]
OK !

**Comment by LucasBerbesson** [comment]
C'est fait 7ddb527

**Comment by GwilhermPoullennec** [comment]
Excellent.
