### ISSUE TITLE
Parler d'emplacement plutôt qu'élévation

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/portail#127]
emplacement décrira ainsi la situation de l'instrument dans l'édifice.
si existant emplacement est alors à faire apparaître dans l'interface (visualisation, liste, carte).

Normalement, la désignation est réserver à une description, par exemple "orgue coffre", par défaut "orgue".

**Comment by GwilhermPoullennec** [comment]
Doc mise à jour par anticipation

**Comment by LucasBerbesson** [comment]
C'est fait de3eabf
