### ISSUE TITLE
[Recherche] Affichage des résultats

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/portail#138]
- On pourrait afficher en haut de la recherche le nombre d'occurences trouvées (de façon à indiquer s'il faut affiner ou non la recherche).

**Comment by Lluke-h** [comment]
Affichage du nombre de résultats en haut de la recherche : feba50c4ea9d89d59d5e87b89b1a826f19178e58 50d2ba31f73b1ce0edd5b41659d75463a82e8ca2
