### ISSUE TITLE
[Recherche] Lancement de la recherche

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/portail#139]
- la loupe de recherche est trop discrète.
- lancement de la recherche sur appui de la touche retour chariot.

**Comment by GwilhermPoullennec** [comment]
J'ai mis la loupe sur fond prune.

**Comment by GwilhermPoullennec** [comment]
Voir aussi : #147

**Comment by LucasBerbesson** [comment]
Je vais regarder ce que je peux faire pour rendre la recherche plus dynamique
