### ISSUE TITLE
Bug d'affichage mini-carte

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/portail#14]
La mini-carte ne s'affiche pas si lat ou lon sont négatifs. Probablement un problème de formattage de chaîne de caractère Javascript.
Peut-être utiliser : |safe plutôt que |escapejs dans le template HTML.

**Comment by LucasBerbesson** [comment]
Fix : b603d5a54954e591e69958b8ebe9fa38e4c529ee
