### ISSUE TITLE
Ordre des départements dans liste déroulante

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/portail#140]
Sur l’écran d’accueil, la liste déroulante des départements, la Haute-Corse et la Corse du Sud se retrouvent après le département du Finistère (29) alors qu’il faudrait que ces départements soient positionnés à leur place, entre le 19 et le 21.

**Comment by GwilhermPoullennec** [comment]
(proposition de Servane)

**Comment by LucasBerbesson** [comment]
Ok c'est fait 9a6fae8

**Comment by GwilhermPoullennec** [comment]
Les Corses t'en sont reconnaissants, merci !
