### ISSUE TITLE
[Carte] couleur des puces

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/portail#145]
La couleur des puces pourrait être typées (monument historiques par exemple, ou taille de l'orgue en fonction de la mini-composition).

**Comment by Lluke-h** [comment]
5e3bbf6 Utilisation du logo monument historique comme marqueur sur la carte pour les orgues concernés

**Comment by GwilhermPoullennec** [comment]
Super.
Il faudrait cependant adoucir la différence entre les puces avec logo et les puces bleue sans logo.
- soit des petites puces bleues (ou autres couleur) carrées comme le logo
- soit intégrer le logo dans une petite puce bordeau
- soit plus bêtement le même type de puce, avec juste un changement de couleur (bleu et bordeau)
