### ISSUE TITLE
Recherche en utilisant la touch Enter [Suggestion]

### ISSUE THREAD

**Issue by Raushka** [inventaire-des-orgues/portail#147]
Je vous propose un affichage direct des réponses à partir d'une recherche par ex sur le facteur soit département etc

**Comment by GwilhermPoullennec** [comment]
C'est possible, mais l'inconvénient serait de ne plus pouvoir lancer de recherche sur un facteur ET un département car la recherche se lancerait dès le choix de l'un ou de l'autre.

**Comment by Raushka** [comment]
Merci pour commentaire

**Comment by LucasBerbesson** [comment]
J'ai fait en sorte que la recherche se lance automatiquement (uniquement depuis la page https://inventaire-des-orgues.fr/orgues). Normalement on peut continuer d'affiner sa recherche même après la sélection d'un premier attribut.

**Comment by GwilhermPoullennec** [comment]
Excellent !
