### ISSUE TITLE
[charte graphique]

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/portail#149]
- Arrondis sur les images à l'intérieur d'une fiche
- La dernière image met beaucoup de temps à se charger
- Arrondir la barre de recherche du lexique

**Comment by LucasBerbesson** [comment]
Tu as déjà fait les arrondis non ?   
Quand tu dis "la dernière image" tu parles de la dernière photo d'orgue dans la liste de résultats après une recherche ? Attention les temps de chargement d'image ne sont pas les mêmes en prod et en dev.

**Comment by Lluke-h** [comment]
Arrondir la barre de recherche du lexique : b023dea9c23cd3a0fcc686e93436ad2b482886e4

**Comment by GwilhermPoullennec** [comment]
- arrondis images : je crois que Guillaume parlait des images à l'intérieur d'une fiche d'un orgue quand on la visualise (et non celle de la liste des orgues, déjà arrondies en effet).

**Comment by GwilhermPoullennec** [comment]
- "dernière image" : pas clair en effet ! Il s'agit de l'image précédent le pied de page, avec les deux enfants de dos.

**Comment by LucasBerbesson** [comment]
Taille des images : 72afdca
