### ISSUE TITLE
Assigner les issues et commenter quand elles sont faites

### ISSUE THREAD

**Issue by LucasBerbesson** [inventaire-des-orgues/portail#152]
Bonjour à tous, 
Est-ce que vous pouvez assigner les issues (quitte à vous les attribuer) et ajouter des commentaires au fil des avancements ; idéalement en citant les commits (de branche dev ou master, ex: 8264d781a75e8cf673d0d).  
Ca permettra d'éviter que 2 personnes travaillent sur la même chose.

**Comment by GwilhermPoullennec** [comment]
OK.
Pour les pull requests du dev vers master, je vous laisse les faire dès qu'il y a correction de bug ou quelques commits d'empilés ?
Merci.
