### ISSUE TITLE
Impossibilité d'enregistrer une composition à cause du calcul du résumé de composition

### ISSUE THREAD

**Issue by Raushka** [inventaire-des-orgues/portail#153]
Après notre conférence Zoom, j'ai essayé de corrigé la *Composition* 
![Screenshot_20200813_151332_com android chrome](https://user-images.githubusercontent.com/69116710/90139974-5d0aed80-dd79-11ea-9ea4-8eedb8b63111.jpg)
et je suis tombée sur une erreur technique (pièce jointe)

**Comment by LucasBerbesson** [comment]
Merci, c'est corrigé 9d9c52958fc5ab !

**Comment by Raushka** [comment]
Cool
