### ISSUE TITLE
Ordre des résultats pour certaines recherches

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/portail#156]
Lorsque l'on lance une recherche sur une ville ou bien un nom d'édifice, on pourrait trier par ordre alphabétique de la ville > du nom d'édifice.

**Comment by LucasBerbesson** [comment]
Aujourd'hui le moteur de recherche utilisé ne permet pas de trier les résultats autrement que par "pertinence" : 
https://github.com/meilisearch/MeiliSearch/issues/730

à l'avenir on pourra peut-être utiliser https://www.algolia.com/for-open-source/

**Comment by patou** [comment]
meilisearch permet maintenant de faire un [tri des résultats lors de la recherche](https://docs.meilisearch.com/reference/features/sorting.html#configuring-meilisearch-for-sorting-at-search-time).

Par contre, comment savoir que l'on est dans une recherche sur le nom d'une ville ?

**Comment by GwilhermPoullennec** [comment]
Intéressant ! Je ne sais.
La fonction ordre alphabétique n'est cependant pas une priorité.
En revanche, si on pouvait afficher d'abord, quelle que soit la recherche, les fiches avec une vignette ce serait très utile.

**Comment by patou** [comment]
C'est déjà le cas, en triant par la completion décroissant. Comme la vignette a un poids important sur la completion.
Mais ce tri ne se fait qu'une fois le tri de pertinence, et je pense qu'il ne faut pas trop changer cela, car sinon, on perd vraiment le système de recherche.

**Comment by GwilhermPoullennec** [comment]
#593
