### ISSUE TITLE
Suppression d'item de Composition 

### ISSUE THREAD

**Issue by Raushka** [inventaire-des-orgues/portail#162]
![Screenshot_20200818_122359_com android chrome](https://user-images.githubusercontent.com/69116710/90502414-112bc000-e14e-11ea-9d37-76ee1e473ed4.jpg)
Bonjour, 
J'ai essayée de supprimer de G.O.de composition d'un petit orgue ajd
Merci pour jeter un coup d'œil 
Raushka

**Comment by LucasBerbesson** [comment]
En effet merci c'est corrigé 468d485

**Comment by Raushka** [comment]
Merci 👌
