### ISSUE TITLE
Une faute d'orthographe 

### ISSUE THREAD

**Issue by guillaume-lb** [inventaire-des-orgues/portail#163]
![Sans titre](https://user-images.githubusercontent.com/67968339/90930611-3729bc80-e3fb-11ea-857c-8ff39b25fbbe.jpg)

Le mot recen"s"és.

**Comment by Raushka** [comment]
Des amis ? 
![IMG_20200824_103629](https://user-images.githubusercontent.com/69116710/91022775-f9dd4e80-e5f5-11ea-9c76-178934917290.jpg)

**Comment by Lluke-h** [comment]
4e17feb
