### ISSUE TITLE
Basses et dessus

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/portail#17]
Pour un jeu de la composition, pouvoir choisir :
- "Basse" : abbréviation possible dans la lecture : "B"
- "Dessus" : abbréviation possible dans la lecture : "D"
- (néant)

**Comment by GwilhermPoullennec** [comment]
Exemple : Hautbois 8 (D)

**Comment by LucasBerbesson** [comment]
Mais ça on ne peut pas déjà le renseigner dans le commentaire ?

**Comment by GwilhermPoullennec** [comment]
Une organiste a demandé à le typer, car c'est assez courant.

**Comment by GwilhermPoullennec** [comment]
On garderait en commentaire l'étendue (exemple : un dessus commence au C3 ou F3 généralement.)

**Comment by LucasBerbesson** [comment]
comme ça ?
<img width="850" alt="Capture d’écran 2020-01-24 à 19 03 11" src="https://user-images.githubusercontent.com/8393585/73092105-3324d300-3edc-11ea-934c-207014ba20b1.png">

**Comment by GwilhermPoullennec** [comment]
Oui !

**Comment by GwilhermPoullennec** [comment]
J'ai une autre idée : pour faire un peu plus simple on garde tel quel (pas ne nouvel attribut).

Eventuellement, à l'affichage, si "(B)" ou "(D)" est présent dans le petit texte de commentaire, on l'affiche à droite du nom du jeu, avant ou à la place de l'astérisque. Qu'en penses-tu ?

**Comment by LucasBerbesson** [comment]
J'ai ajouté le champ de sélection
