### ISSUE TITLE
Enregistrement

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/portail#172]
Peut-on imaginer un autre procédé que le passage obligé systématique par le bouton enregistrer (que l'on risque d'oublier au moins une fois en renseignant toute une fiche).
Enregistrement automatique ?

**Comment by LucasBerbesson** [comment]
L'enregistrement automatique est trop long à mettre en place.   
J'ai ajouté une popup d'alerte quand on essaye de quitter une page sans enregistrer.
