### ISSUE TITLE
Gestion des images

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/portail#174]
Une image portrait n'apparaît en mode paysage dans l'inerface édition.
Conserver les proportions permettrait de ne pas perturber l'utilisateur.

**Comment by LucasBerbesson** [comment]
Ok j'ai changé le code pour garder les proportions sur la gestion des images (ex : https://inventaire-des-orgues.fr/images/5d700169-da5d-406d-9dd3-2fb8c86a714d/). Par contre sur la fiche de détail de l'orgue j'utilise que des vignettes en ratio 4:3 sinon la mosaïque s'agence mal (ex : https://inventaire-des-orgues.fr/detail/orgue-caen-eglise-saint-jean-1280/). En cliquant sur le symbole "+" d'une photo on la retrouve dans ses proportions d'origine.
