### ISSUE TITLE
Pédale vs. Pédalier

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/portail#18]
Dans la composition, l'ensemble sonore joué avec les pieds est la "Pédale" et non le "Pédalier" (ce dernier étant l'objet).

**Comment by LucasBerbesson** [comment]
Du coup c'est dans les "types_claviers" du config.json qu'il faut changer ça non ?

**Comment by GwilhermPoullennec** [comment]
Yes

**Comment by LucasBerbesson** [comment]
C'est bon du coup (au fait, je te laisse Close les issues quand c'est bon)
