### ISSUE TITLE
Mettre permission sur infos de localisation

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/portail#181]
Une permission pour l’ensemble :
- Commune
- Édifice
- Code Insee
- Code Departement
- Departement
- Region

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by LucasBerbesson** [comment]
Les utilisateurs qui n'ont pas la permission orgues.edition_avancee auront ces champs grisés
