### ISSUE TITLE
Vignettes "page  Orgue" 

### ISSUE THREAD

**Issue by guillaume-lb** [inventaire-des-orgues/portail#183]
Sur la page "les orgues" : 
les différentes fiches affiches la photo d'un instrument, or, les photos sont à moitiés pixelisées. Serait-t'il possible d'avoir une meilleure qualité d'image pour ces vignettes ?

**Comment by LucasBerbesson** [comment]
Bonjour Guillaume, 
Les vignettes sont effectivement compressés pour diminuer le temps de chargement de la page. 
Est-ce que tu as un exemple de vignette pixelisée ?

**Comment by guillaume-lb** [comment]
Bonsoir Lucas,

En effet, je supposais bien qu'il était sûrement question de chargement de
page...

À toi de voir, c'est toi le professionnel ;-)

En tout cas voici un exemple :
Sur la vignette d'un orgue et la même image inter fiche.

Bonne matinée
Guillaume



Le mar. 1 sept. 2020 à 17:56, Lucas Berbesson <notifications@github.com> a
écrit :

**Comment by LucasBerbesson** [comment]
Je pense que les images ne sont pas passées dans ton dernier commentaire

**Comment by guillaume-lb** [comment]
Le mer. 2 sept. 2020 à 09:16, Lucas Berbesson <notifications@github.com> a
écrit :

**Comment by GwilhermPoullennec** [comment]
Guillaume, de quel orgue parles-tu par exemple ?

**Comment by guillaume-lb** [comment]
![0_Screenshot_20200902-012501_Chrome](https://user-images.githubusercontent.com/67968339/92043303-21fa4980-ed7c-11ea-9f44-c21d79f58b73.jpg)
![Uploading 1_Screenshot_20200902-012523_Chrome.jpg…]()

**Comment by LucasBerbesson** [comment]
Ok ça marche, je viens d'augmenter la définition des vignettes. Elles font maintenant en moyenne 150Ko. Pour une page de 20 orgues ça fait 3Mo d'images. Si on augmente encore j'ai peur que ça augmente beaucoup le temps de chargement.  
Après ton screenshot est très zoomé (tu es sur tablette ?), normalement sur ordinateur ça donne ça : 


![Capture d’écran 2020-09-03 à 10 49 15](https://user-images.githubusercontent.com/8393585/92093106-39b0ec80-edd3-11ea-9b61-6f148099fe5a.png)

**Comment by GwilhermPoullennec** [comment]
Il faut fermer les volets de l'orgue pour ne plus avoir le problème de pixelisation des tuyaux ;-)
