### ISSUE TITLE
None dans les sous-titres des fiches

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/portail#185]
- si absence désignation : ex : Sainte-Geneviève, Versailles. (Mettre "orgue" par défaut)
- si absence résumé composition (il y a souvent ailleurs "?" par défaut) : ex : Saint-Malo, Saint-Malo. (Toujours ne rien mettre par défaut)

**Comment by LucasBerbesson** [comment]
C'est fait be5e50d
