### ISSUE TITLE
Bug images introuvables

### ISSUE THREAD

**Issue by LucasBerbesson** [inventaire-des-orgues/portail#186]
Est-que qqun a manipulé directement les images dans le dossier media du site ?    
Il y a un problème avec l'orgue de Église Saint-Jacques | Montebourg (Manche)

https://inventaire-des-orgues.fr/detail/orgue-montebourg-eglise-saint-jacques-4139/

**Comment by GwilhermPoullennec** [comment]
Cf. #164 !

**Comment by GwilhermPoullennec** [comment]
Par contre je n'ai pas cogité comment marchent les vignettes... Il faut les "recalculer" ?

**Comment by LucasBerbesson** [comment]
Dans le modèle [Image](https://github.com/inventaire-des-orgues/portail/blob/master/orgues/models.py#L500) le champ `Image.image` est l'image d'origine chargée par l'utilisateur. Les champs `Image.thumbnail et Image.vignette` sont calculés automatiquement à partir de l'image d'origine et stockés dans `/var/www/portail/static/media/CACHE/images`.

Pour changer la définition des vignettes j'ai changé les dimensions des processeurs dans le modèle Image (pas besoin de migrations ici, thumbnail et vignette ne sont pas stockés en base de donnée mais calculés) puis j'ai supprimé le dossier /media/CACHE pour forcer Django à recalculer. La génération des vignettes se fait au moment de leur premier affichage, après l'image est dans le cache.

Le bug de l'orgue Montebourg est lié au fait que des images 'd'origine' stockées en base de données ont été supprimées directement sur le serveur. Du coup Django essaye de retrouver l'image qu'il a en base de données sur le disque et ne la trouve pas.

**Comment by GwilhermPoullennec** [comment]
Merci beaucoup pour l’explication, je n’avais pas aussi supprimer tout le dossier CACHE sans creuser.

Je fais tourner les scripts de correction de la base ce soir ou demain matin.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
