### ISSUE TITLE
Impossibilité d'accès au tableau Github de suivi du projet

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/portail#189]
Notre stagiaire a une erreur 404 sur :
[https://github.com/orgs/inventaire-des-orgues/projects/1](https://github.com/orgs/inventaire-des-orgues/projects/1)

Et vous ?
![0](https://user-images.githubusercontent.com/30436457/92256166-aa3f3280-eed3-11ea-9186-53235bde4e21.jpg)

**Comment by LucasBerbesson** [comment]
chez moi ça fonctionne

**Comment by GwilhermPoullennec** [comment]
c'est bon, sûrement une espace en trop
