### ISSUE TITLE
Evolution schéma de données

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/portail#19]
Cf. JSON de données et configuration

**Comment by LucasBerbesson** [comment]
Est-ce que tu peux me réexpliquer ce que veulent dire les champs orgbase_* ?

**Comment by GwilhermPoullennec** [comment]
Champs qui à terme disparaîtront. Ce sont des URL (_manu) et (_auto) vers un base de données néerlandaise qui répertorie tous les orgues de France ou presque. Les autres champs orgbase sont des champs texte, notamment orgbase_minicompo qui décrit la mini-composition et nous permettra de récupérer à minima toutes les minicompo de France.
Idem pour orgbase_facteurs
Exemple :
http://www.orgbase.nl/scripts/ogb.exe?database=ob2&%250=2028806&LGE=EN&LIJST=lang

Dans le JSON, ce pourrait être sous un même noeud.

**Comment by LucasBerbesson** [comment]
Accessoires devient un champ libre

**Comment by GwilhermPoullennec** [comment]
On ne garde donc que le champ minicompo (équivalent de resume_clavier).

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by GwilhermPoullennec** [comment]
J’ai ajouté un champ adresse, qui permet de distinguer les édifices de même nom sur le territoire d’une même commune.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
