### ISSUE TITLE
La carte n'affiche plus aucun item

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/portail#190]
Le fichier JSON renvoyé est vide après l'orgue de Vaucresson:

Fin du fichier:
...{"pk": 30614, "slug": "orgue-vaucresson-eglise-saint-denys-30614", "commune": "Vaucresson", "edifice": "\u00e9glise Saint-Denys", "latitude": 48.839137919047616, "longitude": 2.158864126190476, "emplacement": null, "references_palissy": null}, {"

**Comment by GwilhermPoullennec** [comment]
/var/www/portail/liste.json

**Comment by LucasBerbesson** [comment]
C'était un problème de permission de cache Nginx depuis qu'on a changé le user nginx. C'est corrigé.

**Comment by GwilhermPoullennec** [comment]
Merci beaucoup pour la correction rapide !
