### ISSUE TITLE
[admin] création d'un orgue : il demande un slug

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/portail#193]
Or on n'a pas encore l'id de l'orgue...

**Comment by LucasBerbesson** [comment]
Effectivement j'avais pas prévu qu'on passe par l'admin pour créer des orgues, je regarde

**Comment by GwilhermPoullennec** [comment]
En attendant, j'ai mis des slug manuellement, avec "1" à la place du pk terminal.

**Comment by GwilhermPoullennec** [comment]
https://github.com/inventaire-des-orgues/indexes/issues/3

**Comment by GwilhermPoullennec** [comment]
Et là, plus besoin de renseigner un slug, mais le slug calculé se termine par "-None".

**Comment by LucasBerbesson** [comment]
Ok j'ai remplacé le pk par la codification dans le slug, ça devrait être bon
