### ISSUE TITLE
Recherche infructueuse

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/portail#196]
Marseille
Saint-François-d’Assise

**Comment by LucasBerbesson** [comment]
Je vais mettre en place un vrai moteur de recherche, ça va dépoter

**Comment by GwilhermPoullennec** [comment]
Point de détail important :
Lorsque l’on recherche un libellé dans « Commune » il faut aller chercher le libellé dans les attributs « Commune » et « Ancienne commune ».

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by LucasBerbesson** [comment]
https://inventaire-des-orgues.fr/orgues/?departement=&query=Guignicourt

**Comment by GwilhermPoullennec** [comment]
Excellent !
