### ISSUE TITLE
Recherche "élastique"

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/portail#2]
Implémenter une recherche souple :
- Pour débuter : simple spilt d'une chaîne de caractère (enlever et séparer "église", "-", " ", et ne pas tenir compte de la casse), de façon à ce qu'une recherche sur "malo" affiche les orgues de Saint-Malo.
- Suppression automatique des espaces en début et fin de saisie
- Puis : ElasticSearch ou équivalent.

**Comment by LucasBerbesson** [comment]
On peut commencer par se brancher à l'API https://api-adresse.data.gouv.fr
