### ISSUE TITLE
Dates approchées dans l'historique

### ISSUE THREAD

**Issue by guillaume-lb** [inventaire-des-orgues/portail#205]
Il y a des dates dont nous ne connaissons pas l'année précisément. Il faudrait peut-être proposer une solution dans le genre  :

Date * exemple 

entre 1960 - 1970 ou un siècle ou "après l’événement "X" d'avant. etc.

**Comment by LucasBerbesson** [comment]
Malheureusement il faut nécessairement un nombre entier pour pouvoir ordonner les dates sur la frise ...
Le plus simple est de mettre une date exacte et de préciser l'approximation dans le commentaire de l'évènement

**Comment by GwilhermPoullennec** [comment]
En revanche il y a possibilité, me semble-t-il, de mettre des intervalles dans le temps (start_date, end_date) :
https://timeline.knightlab.com/docs/json-format.html
Ne serait-ce une solution ?

**Comment by GwilhermPoullennec** [comment]
Et avec `display_date`, voire `background` et les CSS, on doit pouvoir mettre en forme.

**Comment by Anne0905** [comment]
Possibilité de mettre "avant" ou "après" ou > 1850 ou <1850 ?

**Comment by LucasBerbesson** [comment]
<img width="804" alt="Capture d’écran 2021-03-21 à 11 16 21" src="https://user-images.githubusercontent.com/8393585/111902166-4a0d7980-8a3c-11eb-9dcd-d6fbfe7ebf7a.png">
