### ISSUE TITLE
[Frise chronologique] Facteur d'orgue n'apparaît pas

### ISSUE THREAD

**Issue by guillaume-lb** [inventaire-des-orgues/portail#207]
Dans la frise, le remplissage de la case "Facteur d'orgue" n'apparaît pas. 

Il faudrait avoir,

1) L’événement (ex : construction)  
2) L'année ou la date approximatif
**3) Les facteurs d'orgue** (manquant)  
4) Le résumé (CV)

**Comment by LucasBerbesson** [comment]
Normalement le nom du facteur apparaît mnt
<img width="859" alt="Capture d’écran 2020-09-30 à 15 30 50" src="https://user-images.githubusercontent.com/8393585/94691751-f98d4d00-0331-11eb-83ae-6c0a5f4f903f.png">
