### ISSUE TITLE
Problème d'affichage photos

### ISSUE THREAD

**Issue by guillaume-lb** [inventaire-des-orgues/portail#212]
Depuis ce soir, les photos principales que je mets ne veulent pas s'afficher dans les vignettes ?
Sûrement un bug. J'ai rafraîchi mon cache et cela n'a rien fait.

**Comment by LucasBerbesson** [comment]
Bonjour Guillaume, le bug provenait du nouveau moteur de recherche, c'est corrigé

**Comment by guillaume-lb** [comment]
Ok ! Merci beaucoup Lucas.

Le lun. 14 sept. 2020 à 08:42, Lucas Berbesson <notifications@github.com> a
écrit :
