### ISSUE TITLE
Le pourcentage d'avancement de la fiche d'orgues ne fonctionne pas bien

### ISSUE THREAD

**Issue by Raushka** [inventaire-des-orgues/portail#215]
Quand on remplit le fichier des orgues, le pourcentage de remplissage (d'avancement) 
ne marche pas bien. Il est difficile ensuite de trouver l'orgue qu'on a déjà remplie.
Merci de jeter un coup d'œil à ce problème.
Amicalement, 
Raushka

**Comment by GwilhermPoullennec** [comment]
Que voulez-vous dire par "ne marche pas bien" ? Merci.

**Comment by Raushka** [comment]
Probablement , ça n'a pas  bien fonctionné durant la semaine dernière mais maintenant c'est bon : s’affiche correctement le résultat de remplissage. Merci !

**Comment by Raushka** [comment]
Bonjour,

C'est une message de part de Plet :

J’ai rempli plusieurs fiches mais elles ne s'affichent pas à 100%, d'autres
s'affichent à 100% avant même que j'ai fini la composition????

je ne comprends pas bien la logique

J'arrête sur les orgues troyens

_______

Je suis d'accord

Ça marche pas toujours bien

**Comment by GwilhermPoullennec** [comment]
Les points sont attribués pour la composition si un plan sonore est présent... même s'il est vide.
Remplacer par "au moins un jeu présent".
