### ISSUE TITLE
Ajouter le logo de la région Bourgogne-Franche-Comté

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/portail#217]
![langfr-1024px-Bourgogne-Franche-Comté_2016 svg](https://user-images.githubusercontent.com/30436457/94608677-03fe0700-029e-11eb-82e8-529811309a02.png)

**Comment by LucasBerbesson** [comment]
C'est fait (j'ai dû le passer en blanc)
