### ISSUE TITLE
[edition] Liste événements non responsive

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/portail#220]
<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by LucasBerbesson** [comment]
Est-ce que c'est toujours le cas ?   
Il s'agit de la liste en mode édition ou sur la fiche de l'orgue ?

**Comment by GwilhermPoullennec** [comment]
Cela semble marcher !
