### ISSUE TITLE
Liste facteurs : suppressions doublons

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/portail#221]
Laurent Plet

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by LucasBerbesson** [comment]
Il faut faire un script manage.py qui supprime les doublons sans perdre d'informations.
Qqch du genre :

⚠️ code absolument pas testé ⚠️ 

```python
from django.db.models import Count
from orgues.models import Facteur, Evenement

doublons = Facteur.objects.values('nom').annotate(nom_count=Count('nom')).filter(nom_count__gt=1)
for doublon in doublons:
    facteurs = Facteur.objects.filter(nom=doublon['nom'])
    facteur_quon_garde = facteurs[0]
    facteurs_qui_disparaissent = facteurs[1:]
    for facteur_qui_disparait in facteurs_qui_disparaissent:
        for evenement in Evenement.objects.filter(facteurs=facteur_qui_disparait):
            evenement.facteurs.remove(facteur_qui_disparait)
            evenement.facteurs.add(facteur_quon_garde)
        facteur_qui_disparait.delete()
```
⚠️ code absolument pas testé ⚠️

**Comment by GwilhermPoullennec** [comment]
Célestin, j'ai utilisé le script delete_doublons_facteurs sur le serveur, visiblement sans trop de casse.
Avant d'utiliser l'autre (replace_facteurs), puis-je vous demander une petite amélioration :
que les colonnes 2 à n du fichier CSV soient utilisées pour remplacer un facteur par plusieurs.

ex : Jaquot-Dider;Nicolas Jaquot;Charles Didier;
remplacera "Jaquot-Didier" par ["Nicolas Jaquot","Charles Didier"] en BD

**Comment by CelestinHuet** [comment]
C'est sur la branche dev.
