### ISSUE TITLE
[visu] Champs à faire apparaître

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/portail#225]
- Les commentaires  sur la mécanique note
- Les commentaires sur le tirage des jeux
- Le tempérament
- Le diapason
- La description de la tuyauterie

**Comment by LucasBerbesson** [comment]
C'est fait
![Capture d’écran 2020-10-19 à 17 33 01](https://user-images.githubusercontent.com/8393585/96472797-2944bc00-1231-11eb-8212-3354a208a90d.png)
