### ISSUE TITLE
[historique] Empêcher le Wysiwyg dans le descriptif d'un évènement

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/portail#226]

**Comment by LucasBerbesson** [comment]
C'est fait. 
J'ai aussi nettoyé les évènements existants qui contenaient du HTML. 
Au passage j'ai remarqué que les évènement du type "Classement au titre des monuments historiques" étaient formatés un peu bizarrement parfois

**Comment by GwilhermPoullennec** [comment]
Merci beaucoup.
Pour les monuments historiques, il faudrait que je charge tout. Comment forcer mettre un retour chariot si on n'est plus en HTML ?

**Comment by LucasBerbesson** [comment]
Il faut ajouter des `\r\n`
