### ISSUE TITLE
[liste] les anciennes communes ne s'affichent pas

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/portail#227]
![bug_slash](https://user-images.githubusercontent.com/30436457/96150230-76abeb00-0f0a-11eb-8b11-a566a3dfe016.png)

**Comment by LucasBerbesson** [comment]
Je pense qu'il va falloir dire aux utilisateurs de laisser vide quand il faut laisser vide :)

![Capture d’écran 2020-10-16 à 18 05 18](https://user-images.githubusercontent.com/8393585/96281832-2f8d2b00-0fda-11eb-903c-682def79e33a.png)
