### ISSUE TITLE
Ajouter une page de description du taux d'avancement

### ISSUE THREAD

**Issue by LucasBerbesson** [inventaire-des-orgues/portail#229]
Certaines personnes ne comprennent pas le taux d'avancement

**Comment by LucasBerbesson** [comment]
C'est fait 
J'ai ajouté le détail des scores en cours et des liens pour voir où ça se passe 

![Capture d’écran 2020-10-19 à 17 27 23](https://user-images.githubusercontent.com/8393585/96472189-7b391200-1230-11eb-97fd-27d074fdc1bb.png)

**Comment by GwilhermPoullennec** [comment]
Excellent !
