### ISSUE TITLE
[Visualisation] Les infos-bulles des images affichent du HTML brut

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/portail#232]

**Comment by LucasBerbesson** [comment]
Est-ce que tu as un lien où je peux retrouver le pbm ?

**Comment by GwilhermPoullennec** [comment]
![bug_infobulle_html](https://user-images.githubusercontent.com/30436457/99145277-c1d22e80-266d-11eb-8476-4d8c3c590b76.jpg)

**Comment by GwilhermPoullennec** [comment]
Survol des images autres que l'image principale en mode [visualisation].
