### ISSUE TITLE
Ordre d'affichage des facteurs d'orgue

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/portail#238]
(remarques de M. Laurent Plet).

Quand on remplit la frise  chronologique, tout est mis en bon ordre
1. Quand on lit la fiche finie; les facteurs sont toujours en ordre chronologique mais sans retour à la ligne entre chaque intervention, ce qui rend la lecture peu claire
2. En mode liste il n'y a que les noms des facteurs mais dans un ordre apparemment alphabétique; c'est troublant
Si on pouvait afficher les facteurs par ordre chronologique, ce serait mieux, il me semble

**Comment by GwilhermPoullennec** [comment]
J'ai mis des <br/>, peut-être faut mettre sous forme de liste ?

**Comment by GwilhermPoullennec** [comment]
2. Je ne sais si le dernier alinéa peut être traité, sans ralentir la recherche et l'affichage.

**Comment by LucasBerbesson** [comment]
Message bien reçu, tout est rentré dans l'ordre
