### ISSUE TITLE
Ouverture des images

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/portail#24]
Ne pas les ouvrir en grand dans le navigateur : visionneuse basique en CSS seul ou JS ?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by LucasBerbesson** [comment]
C'est bon j'ai ajouté un plugin

**Comment by GwilhermPoullennec** [comment]
Ajouter légende sous la photo, à partir du champ crédit 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
