### ISSUE TITLE
Ajout champ : Facteurs responsables de l'entretien de l'instrument

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/portail#245]

**Comment by CelestinHuet** [comment]
A quel endroit faut-il ajouter le champ entretien dans la partie "fiche à compléter" ?

**Comment by GwilhermPoullennec** [comment]
Je n’y ai pas encore réfléchi.
Que proposez-vous ?

**Comment by CelestinHuet** [comment]
Je le mettrais dans la partie Informations générales, juste avant ou juste après "organisme auquel s'adresser".

**Comment by GwilhermPoullennec** [comment]
Cet endroit me semble le bon !
Il faudra bien faire les migrations en local (avec l'option -merge) en s'assurant que vous êtes au même niveau dans les migrations que le serveur, les appliquer en local, les ajouter au dépôt Git et le commiter avec l'évolution.

**Comment by CelestinHuet** [comment]
D'accord. Mais je ne vois pas bien l'intérêt des migrations puisque je ne touche pas au modèle de la base de données, je ne fait qu'ajouter un champ dans le formulaire.

**Comment by GwilhermPoullennec** [comment]
Les informations du champ sont bion liées au modèle de donnée, non ? (liste d'objets Facteur)

**Comment by CelestinHuet** [comment]
Le champ du formulaire pour l'entretien doit récupérer un Facteur. Mais dans le modèle de la base de données, il y a déjà un champ entretien.

**Comment by CelestinHuet** [comment]
J'ai ajouté une ligne "entretien" dans forms.py, class OrgueGeneralInfoForm(), class meta, fields. Mais je ne parviens pas à modifier le champ entretien lorsque le formulaire est validé. Manque-t-il une autre ligne ?

**Comment by CelestinHuet** [comment]
C'est bon, problème réglé. Une autre ligne n'est pas nécessaire.
