### ISSUE TITLE
Modification de la codification en BDD

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/portail#250]
Le script replace_codes.py existe déjà, mais gère seulement les fichiers et les images.
Doit-on recalculer vignettes ? Autres dépendances ?

**Comment by GwilhermPoullennec** [comment]
replace_codes.py

**Comment by LucasBerbesson** [comment]
Faire attention au déplacement des vignettes recadrées qui sont dans le dossier CACHE

**Comment by CelestinHuet** [comment]
Concernant les fichiers dans le script replace_code, j'ai l'impression qu'il y a un souci dans l'export des orgues de données via l'API. Sur l'image suivante, le fichier file est un fichier provenant de l'export de la base de données. Le fichier file1 est un fichier que j'ai uploadé en local. Les chemins entre les deux sont diférents. Celui de file.path est incohérent : il commence par un chemin relatif pour finir par une url. Dans le fichier db.sqlite3, ce sont des url qui sont fournies pour les fichiers. Comment faire pour contrôler l'export via l'API ?
![image](https://user-images.githubusercontent.com/79277114/114912334-29a8c300-9e20-11eb-8b3d-14d01ec3fc34.png)

**Comment by GwilhermPoullennec** [comment]
Il faut choisir une convention : chemins relatifs ou chemins absolus

- soit en modifiant FichierSerializer dans orgues/api/serializers.py pour qu'il crache des chemins relatifs dans le JSON (ce qui l'allègera au passage).
- soit modifier import_data.py à la ligne 159 pour, en important, passer de l'absolu au relatif (ne garder par exemple que le nom du fichier et deux niveaux de sous-répertoire).

**Comment by GwilhermPoullennec** [comment]
#457
