### ISSUE TITLE
Pouvoir charger plusieurs photos d'un seul coup

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/portail#260]
En rendant obligatoire la mention crédit, qui sera valable pour toutes les photos.

**Comment by LucasBerbesson** [comment]
Il faudra prévoir d'utiliser une librairie du type https://www.dropzonejs.com/ pour rendre le chargement plus fluide

**Comment by LucasBerbesson** [comment]
C'est fait, on peut charger plusieurs images à la fois. 
Du coup l'ajout des légendes se fait après coup.
