### ISSUE TITLE
Création de la codification depuis la plate-forme

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/portail#267]

**Comment by GwilhermPoullennec** [comment]
L'algorithme de codification est ici : https://github.com/inventaire-des-orgues/paillasse/blob/master/utilsorgues/codification.py

**Comment by CelestinHuet** [comment]
#248

**Comment by GwilhermPoullennec** [comment]
Il faudrait créer une vue / formulaire : "Créer un nouvel orgue" (permissions restreinte).

**Comment by GwilhermPoullennec** [comment]
Utiliser le code géographique national de l'INSEE sous forme CSV (liste des communes)
