### ISSUE TITLE
Accessoire : faire plus simple

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/portail#27]
Il doit y avoir moyen de faire plus simple pour les accessoires, genre texte libre vérifiant une regexp... à discuter au besoin.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by GwilhermPoullennec** [comment]
Ce sera une liste de chaînes de caractères. Idem donc dans le JSON, commes les PM.
Liste prédéfinie pour choix les plus courants + possibilité d'une simple chaîne de caractère.
(Un peu à la façon de labels).

Liste prédéfinie =
- Tremblant
- Trémolo
- Accouplement Pos./G.O.
- Accouplement Réc./G.O.
- Accouplement Pos./Réc.
- Accouplement Réc./Pos.
- Tirasse Pos.
- Tirasse Réc.
- Tirasse G.O.
- Anches G.O.
- Anches Pos.
- Anches Réc.

**Comment by GwilhermPoullennec** [comment]
Affichage : Simple texte, en-dessous de la composition.

**Comment by LucasBerbesson** [comment]
Fait, finalement c'est géré via la base de données (accessoires dans le config.json)
