### ISSUE TITLE
Permettre le dépôt de contenus audio

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/portail#271]
En limitant à 2Mo

**Comment by LucasBerbesson** [comment]
C'est normalement déjà possible via l'onglet "Fichier" qui accepte n'importe quel format.   
Les navigateurs proposent des lecteurs audio par défaut quand on clique sur un lien qui a une extension .mp3 par exemple.

**Comment by GwilhermPoullennec** [comment]
Cela marche !
