### ISSUE TITLE
Ajouter le logo de la région Bretagne

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/portail#275]
Bro ghoz ma bro...
https://www.youtube.com/watch?v=qfFDtVKndto

**Comment by GwilhermPoullennec** [comment]
[Bloc-marque-horizontal.zip](https://github.com/inventaire-des-orgues/portail/files/5765528/Bloc-marque-horizontal.zip)
[Bloc-marque-vertical.zip](https://github.com/inventaire-des-orgues/portail/files/5765534/Bloc-marque-vertical.zip)

**Comment by Amaryllis25** [comment]
> 
> 
> [Bloc-marque-horizontal.zip](https://github.com/inventaire-des-orgues/portail/files/5765528/Bloc-marque-horizontal.zip)
> [Bloc-marque-vertical.zip](https://github.com/inventaire-des-orgues/portail/files/5765534/Bloc-marque-vertical.zip)

Il s'agit du logo Centre Val de Loire. C'est celui-ci qu'on doit ajouter, ou doit-on le rajouter en plus du logo de la Bretagne ?

**Comment by GwilhermPoullennec** [comment]
Les deux régions !

**Comment by GwilhermPoullennec** [comment]
- descendre le logo Bourgogne en seconde ligne (avec les logos Bretagne et Centre)

**Comment by GwilhermPoullennec** [comment]
- équilibrer la taille des logos (réduire légèrement le logo Centre, augmenter légèrement le logo Bretagne)

**Comment by GwilhermPoullennec** [comment]
- centrer les logos

**Comment by Elliot902** [comment]
Pour centrer les logos qui sont dans "portail/templates/footer.html", j'agis sur "portail/static/static_dirs/polo/_footer.scss". Or ça ne fonctionne pas. Est-ce que les fichiers sont bien liés ? J'imagine que oui mais je n'arrive pas à repérer où le voir.

**Comment by Amaryllis25** [comment]
#326

**Comment by Amaryllis25** [comment]
Je vais bientôt mettre le code, j'ai déjà centré tous les logos et fait tout les rajouts d'images nécessaires normalement. Pour ce genre de manip tu peux modifier directement le style sur les lignes html.

**Comment by LucasBerbesson** [comment]
Attention un fichier scss n'est pas la même chose qu'un fichier css.
Les fichiers .scss doivent être compilés en css.  
Une fois la modification faite il faut [installer sass](https://sass-lang.com/) et lancer la commande 
```
sass static/static_dirs/polo/scss/style.scss static/static_dirs/polo/scss/style.css
```

La modification directe sur les lignes html n'est pas la solution la plus propre.  
Sinon il existe aussi des classes prédéfinies qui peuvent être utiles comme `text-center` (cf [bootstrap](https://getbootstrap.com/))

**Comment by Amaryllis25** [comment]
D'accord je vais tester cela pour essayer de centre les images, plutôt qu'une méthode margin, merci beaucoup !

**Comment by Amaryllis25** [comment]
Eliott si tu le souhaites je peux pousser ce que j'ai déjà et tu peux essayer de centrer les images "plus proprement" que ce que j'ai ? Cela ne me dérange pas du tout.

M. Berbesson, les classes prédéfinies sont-elles tout aussi "propre" que de modifier directement les fichiers .scss ?

**Comment by GwilhermPoullennec** [comment]
Oui puisqu’existent normalement toutes les classes basiques utiles.
La personnalisation n’intervenant que pour des choses plus chiadées.

**Comment by Amaryllis25** [comment]
D'accord merci beaucoup !

**Comment by Elliot902** [comment]
Oui @Amaryllis25 je peux me charger du centrage plus propre.

**Comment by Amaryllis25** [comment]
D'accord je te mets tout ça et je te laisse le modifier !
________________________________
De : Elliot902 ***@***.***>
Envoyé : mercredi 24 mars 2021 16:54
À : inventaire-des-orgues/portail ***@***.***>
Cc : Amaryllis Vignaud ***@***.***>; Mention ***@***.***>
Objet : Re: [inventaire-des-orgues/portail] Ajouter le logo de la région Bretagne (#275)


Oui @Amaryllis25<https://github.com/Amaryllis25> je peux me charger du centrage plus propre.

**Comment by GwilhermPoullennec** [comment]
On ne garde que le ticket général #335
