### ISSUE TITLE
Accès impossible docs

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/portail#276]
![Accès impossible HSTS](https://user-images.githubusercontent.com/30436457/104025668-43a18c80-51c5-11eb-841a-f08a0a631ecd.png)

**Comment by LucasBerbesson** [comment]
Hello !
C'est corrigé, docs.inventaire-des-orgues n'avait plus de certificat SSL, on avait du le supprimer par inadvertance
A+

**Comment by GwilhermPoullennec** [comment]
Merci pour la correction.
Je retiens que les problèmes d'accès bloquants sont toujours dû à des histoires de certificats !
