### ISSUE TITLE
Depuis un évènement on ne peut ajouter un nouveau facteur

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/portail#278]

**Comment by LucasBerbesson** [comment]
Normalement un lien apparaît à l'issue d'une recherche infructueuse
![Capture d’écran 2021-01-29 à 17 48 17](https://user-images.githubusercontent.com/8393585/106303341-50605000-625a-11eb-9d69-9d6358573ae9.png)

**Comment by GwilhermPoullennec** [comment]
Cela efface les autres facteurs de l'évènement.
