### ISSUE TITLE
Les photos portraits apparaissent à l'horizontale

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/portail#282]
[](https://inventaire-des-orgues.fr/detail/orgue-vouvant-eglise-notre-dame-de-lassomption-fr-85305-vouva-ndasso1-x/)

**Comment by LucasBerbesson** [comment]
Est-ce que tu as un exemple ? 
Le pbm vient peut-être des "metas" informations de l'image

**Comment by GwilhermPoullennec** [comment]
https://inventaire-des-orgues.fr/orgues/?departement=&query=vouvant

**Comment by GwilhermPoullennec** [comment]
https://inventaire-des-orgues.fr/detail/orgue-vouvant-eglise-notre-dame-de-lassomption-fr-85305-vouva-ndasso1-x/

**Comment by LucasBerbesson** [comment]
ça devrait mieux marcher mnt

**Comment by GwilhermPoullennec** [comment]
YES !
