### ISSUE TITLE
[Carte] Filtrage avancé

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/portail#286]
- par facteur d'orgue
- avec une case à cocher optionnelle : évènement = construction OU reconstruction, qui permet de ne pas tenir compte des entretiens et petites interventions

**Comment by LucasBerbesson** [comment]
La récupération des orgues pour la carte se fait ici : 
https://github.com/inventaire-des-orgues/portail/blob/4abd3aa38d7c7468566e6a28b161a25626066708/orgues/views.py#L76

On pourrait imaginer ajouter des paramètres GET dans la requête pour filtrer les résultats

**Comment by LucasBerbesson** [comment]
#381

**Comment by CelestinHuet** [comment]
Pouvoir faire un reset du formulaire.

**Comment by CelestinHuet** [comment]
Orgues dans le Golf de Guinée après avoir filtré par facteurs.
