### ISSUE TITLE
[Carte] Ajouter l'emplacement des manufactures d'orgues

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/portail#287]

**Comment by GwilhermPoullennec** [comment]
Liste des facteurs sur le site d'Orgue en France, à géocoder.

**Comment by GwilhermPoullennec** [comment]
Le modèle actuel n'affiche sur la carte que des objets orgues, il faudrait créer une nouvelle classe "Atelier", ou bien encore plus fort ajouter à la classe "Facteur" une liste de coordonnées lat/lon (le ou les ateliers de ce facteur).

**Comment by LucasBerbesson** [comment]
A terme je pense qu'il faudra un menu de navigation à côté de la carte pour éviter de faire une trop grosse requête en base de données en voulant récupérant tous les orgues + tous les facteurs ...

**Comment by GwilhermPoullennec** [comment]
OK. Ceci dit, il n'y a plus qu'une centaine d'ateliers de facture d'orgue en France.

**Comment by GwilhermPoullennec** [comment]
Lat et lon sont ajoutés en attributs de la classe Facteurs.

Chers géographes, à vous de jouer pour compléter les données et implémenter sur la carte (avec une couleur de puce dédiée).
Je vous invite à cette fin à géocoder les informations suivantes :
https://www.orgue-en-france.org/linstrument/informations-pratiques/annuaire-facteurs-dorgues/
