### ISSUE TITLE
[Edition][Composition] Ne pas tenir compte des accents dans le choix du jeu

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/portail#291]
Exemple : trouver Flûte en tapant "flu" au clavier (sans être obligé de mettre "flû").

**Comment by LucasBerbesson** [comment]
C'est une recherche SQL qui se fait ici : 
https://github.com/inventaire-des-orgues/portail/blob/4abd3aa38d7c7468566e6a28b161a25626066708/orgues/views.py#L331
Malheureusement sqlite3 ne permet pas de faire des recherches "approximatives".
2 options : 
- Créer un nouveau champ `TypeJeu.nom_sans_accent` qui serait une copie de `TypeJeu.nom` et qui servirait uniquement à faire des recherches
- Créer un nouvel index pour les jeux dans le moteur de recherche meilisearch (actuellement utilisé uniquement pour les orgues) et brancher les menus déroulants dessus

**Comment by GwilhermPoullennec** [comment]
#292

**Comment by GwilhermPoullennec** [comment]
Je suis plutôt pour la première solution basique proposée (nouveau champ).
Ne serait-ce que parce que meilisearch est galère à installer sous mon poste de développement Windows.

**Comment by LucasBerbesson** [comment]
Ok, mais du coup tu ne peux pas faire de recherche sur les orgues en local ? 
Tu as testé la commande curl ? 

https://docs.meilisearch.com/learn/getting_started/installation.html#download-and-launch

**Comment by GwilhermPoullennec** [comment]
Ils n'ont pas l'air d'aimer Microsoft, si ?

get_os() {
    os_name=$(uname -s)
    case "$os_name" in
    'Darwin')
        os='macos'
        ;;
    'Linux')
        os='linux'
        ;;
    *)
        return 1
    esac
    return 0

**Comment by GwilhermPoullennec** [comment]
Petit progrès, j'ai récupéré une version Win sur Github. Mais ne parviens pas encore à la faire tourner sur PC.

**Comment by LucasBerbesson** [comment]
Je viens de brancher la liste des types de jeux à meilisearch

**Comment by GwilhermPoullennec** [comment]
Superbe.
Et pour les accessoires ?

**Comment by LucasBerbesson** [comment]
Il faudra le faire je pense oui. Et sur les facteurs aussi.
