### ISSUE TITLE
[Edition][Composition] Recherche d'un jeu : ordre des items dans le menu déroulant

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/portail#292]
Dans la liste déroulante, mettre les flûtes ensemble :
Flûte 16'
Flûte 8'
Flûte 4'
Flûte 2'

**Comment by GwilhermPoullennec** [comment]
![menuderoulantjeux](https://user-images.githubusercontent.com/30436457/108488744-068ae880-72a1-11eb-9f98-b1d1acd9cbe7.jpg)

**Comment by LucasBerbesson** [comment]
Aujourd'hui le tri se fait par nombre d'utilisations ici :
https://github.com/inventaire-des-orgues/portail/blob/4abd3aa38d7c7468566e6a28b161a25626066708/orgues/views.py#L332


mais on peut remplacer par 
```python
return queryset.order_by('nom')
``` 
ou même
```python
from django.db.models.functions import Lower
...
return queryset.order_by(Lower('nom'))
```
pour être insensible à la casse
