### ISSUE TITLE
erreur 404 : personnaliser

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/portail#293]
Personnaliser l'erreur 404 pour faire patienter en l'abence des livres numérisés :
 https://inventaire-des-orgues.fr/media/34/FR-34079-C_HER-STPAUL1-C/fichiers/FR-34079-C_HER-STPAUL1-C.pdf

Afficher la même erreur 404 que celle par défaut (avec le bouton retour vers l'accueil)
plus un message : 'les livres d'inventaire numérisés seront bientôt disponibles !'

**Comment by GwilhermPoullennec** [comment]
(https://inventaire-des-orgues.fr/media) renvoie une erreur 403
(https://inventaire-des-orgues.fr/media/autrechose) renvoie une 404 sans template

**Comment by GwilhermPoullennec** [comment]
Pourquoi Django n'attrape-t-il pas cette 404 et 403 ?
Faut créer une vue /media ?

**Comment by GwilhermPoullennec** [comment]
Visiblement, passer par httpd.conf

```
location /404.html {
   alias /var/www/errors/404.html
}
error_page 404             /404.html;
```

**Comment by LucasBerbesson** [comment]
Actuellement la page https://inventaire-des-orgues.fr/error/404/ utilise le moteur de template de Django pour générer le HTML.   
Il faut "enregistrer-sous" la page générée par Django au format HTML et la stocker qqpart sur le serveur ou nginx puisse la retrouver facilement, par exemple ici : `/var/www/errors/404.html`

Par contre si on change l'aspect de cette page il faudra penser à mettre à jour `/var/www/errors/404.html`
