### ISSUE TITLE
[Recherche] Comment faire mieux comprendre que le champ département est un filtre ?

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/portail#297]
![recherche](https://user-images.githubusercontent.com/30436457/108492940-05a88580-72a6-11eb-8f14-823de67c86c6.jpg)

**Comment by Amaryllis25** [comment]
Pensez-vous qu'il faille changer "Département" par "Choix du département", pour mieux faire comprendre qu'il s'agit d'un filtre ?
![image](https://user-images.githubusercontent.com/79219571/110813044-6e24ca00-8288-11eb-89d3-afe00ea0c21a.png)

**Comment by GwilhermPoullennec** [comment]
Je mettrai plutôt "Filtre par département"
Mais pour l'instant ne commitons pas, on en reparle à plusieurs.

**Comment by patou** [comment]
Je pense que déjà il manque un indicateur qui montre que l'on est sur une liste déroulante : 
![image](https://user-images.githubusercontent.com/841858/114736527-7324df80-9d46-11eb-91bd-4cc7944b366c.png)

Il y a un style qui annule le style par défaut de la liste déroulante et affiche une image à la place, sauf que l'image n'est pas présent dans le projet.

**Comment by GwilhermPoullennec** [comment]
Oui, d'ailleurs il me semble que cela génère un paquet de n fois la même erreur dans les logs (si l'image en question est bien quelque chose du stype, de mémoire : arrow-machinchouette.png)

**Comment by patou** [comment]
Oui l'image est : images/dropdown-arrow.png

**Comment by patou** [comment]
Pourquoi fermer cette MR ? il y a toujours rien qui permet de savoir que c'est un champ de filtre !
Qui pourrait nous fournir l'image images/dropdown-arrow.png ?
