### ISSUE TITLE
[Taux d'avancement]

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/portail#298]
![score](https://user-images.githubusercontent.com/30436457/108493327-7a7bbf80-72a6-11eb-9222-56a0c172650c.jpg)

**Comment by GwilhermPoullennec** [comment]
- Baisser la note de la soufflerie et des sommiers (voire supprimer pour les sommiers).

**Comment by GwilhermPoullennec** [comment]
Supprimer une fois la géolocalisation achevée les notes sur communes, département, région.

**Comment by GwilhermPoullennec** [comment]
Augmenter note des claviers.

**Comment by LucasBerbesson** [comment]
Normalement il suffit de modifier https://github.com/inventaire-des-orgues/portail/blob/05c748c3e4823a5f6499ea561cf17e53cf75690b/orgues/models.py#L496
