### ISSUE TITLE
Affichage sur smartphone

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/portail#3]
Sur petits écrans :
- Affichage du cartouche latéral de résumé en début et non fin.
- Comment afficher la frise ?
- N'afficher qu'un orgue par ligne sur la page principale et non trois.

**Comment by LucasBerbesson** [comment]
J'ai amélioré le premier et le dernier point.   
Pour la frise, aujourd'hui elle s'affiche sur mobile, est-ce que tu veux la cacher ?

**Comment by GwilhermPoullennec** [comment]
Gardons la frise sur mobile, elle s'affiche plutôt correctement, c'est d'autres éléments du flux qui sont plus chaotiques.

**Comment by LucasBerbesson** [comment]
Ca devrait être mieux avec le dernier commit

**Comment by LucasBerbesson** [comment]
Par contre je n'ai pas travaillé l'affichage smartphone en mode édition, il y a trop de champs de toutes façons, je pense qu'on le fera toujours depuis un ordi non ?

**Comment by GwilhermPoullennec** [comment]
Oui, pas de mode édition adapté au smartphone.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
