### ISSUE TITLE
Expression : par clavier et non pour toute la tuyauterie

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/portail#30]

**Comment by LucasBerbesson** [comment]
Dans le cartouche de résumé : expressif si un des claviers est expressif

**Comment by GwilhermPoullennec** [comment]
Idée pour faire plus simple : on le renseigne dans la liste des accessoires.
Exemple : Expression Récit

**Comment by GwilhermPoullennec** [comment]
Voire même, pour faire plus simple que plus simple : on ne précise pas l'information, à part dans le nom du plan sonore "Récit expressif".

**Comment by LucasBerbesson** [comment]
Je l'ai ajouté au niveau des claviers
