### ISSUE TITLE
[Carte de la page d'accueil] Calcul des pourcentages erroné

### ISSUE THREAD

**Issue by Johan-Leclercq** [inventaire-des-orgues/portail#300]
Pour certaines régions, la somme des pourcentages des orgues triés en fonction de leur état n'atteint pas 100%. L'écart peut aller de 1 à 4%.
(Par exemple, Normandie : 15% + 1% +1% +80%)

**Comment by GwilhermPoullennec** [comment]
Vérifier si tous les états figurent bien : non renseigné + quatre niveau d’état

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Johan-Leclercq** [comment]
Résolu :
Dans templates\accueil.html l206 :
> var bons = Math.round(100 * (data.bon || 0) / total) + " %";

Les orgues en état "très bon" ne sont pas pris en compte (la var bons sert pour donner le pourcentage des bons et très bons) 

Résolution  (testée en local) :
> var bons = Math.round(100 * ((data.bon || 0)+(data.tres_bon || 0)) / total) + " %";
