### ISSUE TITLE
 [Carte de la page d'accueil] Cas des zones sans orgues (par exemple : Mayotte)

### ISSUE THREAD

**Issue by Johan-Leclercq** [inventaire-des-orgues/portail#301]
Mayotte n'a aucun orgue recensé et cela impacte l'affichage des pourcentages d'orgues triés selon leur état.

La valeur de pourcentage d' "état inconnu" se met à 0%, tandis que les 3 autres pourcentages conservent les valeurs qu'ils avaient pour la région précédemment sélectionnée.

(Par exemple, si on passe d'Occitanie à Mayotte, on a 2% 1% 1% 0%. Si on passe de Réunion à Mayotte, on a  0% 0% 0% 0%)

**Comment by LucasBerbesson** [comment]
Il faut adapter la fonction : https://github.com/inventaire-des-orgues/portail/blob/4abd3aa38d7c7468566e6a28b161a25626066708/orgues/views.py#L87 pour s'assurer que le dictionnaire `etats` contient bien tous les états listés dans https://github.com/inventaire-des-orgues/portail/blob/05c748c3e4823a5f6499ea561cf17e53cf75690b/orgues/models.py#L46 quitte à valoir 0

**Comment by Johan-Leclercq** [comment]
Résolu : 
Dans templates\accueil.html  l211 : 
> var bons, alteres, degrades, inconnus = "0 %";
L'attribution des variables ci-dessous semblait ne mettre à jour que la dernière variable de la liste.

Je crois que l'attribution de valeurs en chaine avec des virgules en séparateur est une spécificité de python et ne marche pas en js.

Résolution (testée en local) :
> var bons = "0 %";
> var alteres = "0 %";
> var degrades = "0 %";
> var inconnus = "0 %";
