### ISSUE TITLE
Carte page d'accueil

### ISSUE THREAD

**Issue by Amaryllis25** [inventaire-des-orgues/portail#307]
Bonjour M. Berbesson,

J'aimerais avoir de plus ample information sur la façon dont a été créée la carte interactive en bas de la page d'accueil du site ?
En effet il semble que les contours ait été rentrés "à la main", et je ne comprend pas vraiment la façon dont ont été construite les coordonnées.

Bonne soirée !

**Comment by LucasBerbesson** [comment]
Bonjour, 
Il s'agit d'une carte svg (https://fr.wikipedia.org/wiki/Fichier:Regions_France_2016.svg) que j'ai récupéré sur wikipedia et que j'ai adapté sur illustrator pour changer ses couleurs.

**Comment by Amaryllis25** [comment]
D'accord, après avoir regardé le site, je voulais confirmation de comment récupérer les contours : je clique sur le svg et je fais examiner l'élément pour récupérer le contour ?

La résolution prise pour l'image des régions est bien 575px par 575 px ?

**Comment by LucasBerbesson** [comment]
J'ai laissé une copie [ici](https://github.com/inventaire-des-orgues/portail/blob/master/static/static_dirs/img/france.svg)

**Comment by Amaryllis25** [comment]
D'accord, je viens de faire un essai avec une ligne au hasard d'un svg département, je dois juste réfléchir à comment je vais me débrouiller pour faire ça !

Je pensais les mettre en cachés (hidden), et lorsqu'on clique sur une région, elles disparaissent pour laisser place aux départements de la région en question ?

En fait il y a des histoires de résolutions aussi, je vais me renseigner.

**Comment by Amaryllis25** [comment]
![image](https://user-images.githubusercontent.com/79219571/110317779-e41cfd00-800c-11eb-905f-44c29e8ffa54.png)

**Comment by Amaryllis25** [comment]
Bonjour M. Berbesson !
Du coup j'ai mieux compris maintenant le principe du svg. J'étudie un peu le code JQuery (j'avoue que cela à l'air plus simple que du javascript) que vous avez écrit concernant la page d'accueil. Pour récupérer les données sur les départements, il faut que je m'inspire de la requête précédente avec régions pour accéder aux données par département ? Par exemple quand je change #selected-regions par selected-departement, cela ne marche pas. Pourriez-vous m'aiguiller ?

**Comment by Amaryllis25** [comment]
D'accord ! Mais je pensais faire une carte qui, lorsqu'on clique sur une région, passe au niveau département (et donc affiche uniquement les départements concernés par la région) : avec une seule requête ajax cela est-il aussi réalisable ?
J'avoue avoir fait peu d'Ajax donc j'ai un peu de mal à visualiser, même si j'ai compris ce qui était écrit.

**Comment by Amaryllis25** [comment]
Bonjour M. Berbesson ! J'ai juste une petite question, qu'est-ce que signifie le xmlns dans les lignes des svg ?
![image](https://user-images.githubusercontent.com/79219571/110782382-5a1ca080-8267-11eb-8244-29bfc53e3380.png)

**Comment by LucasBerbesson** [comment]
bonjour, d'après google c'est un attribut qui sert à préciser la version du SVG

**Comment by Amaryllis25** [comment]
D'accord merci !
