### ISSUE TITLE
Passer en argument le champ à modifier dans un script manage.py

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/portail#308]
Typiquement, j'aimerais que dans la ligne ci-dessous l'attribut designation puisse être une variable passée en argument au script et non écrit en dur.

Orgue.objects.filter(designation=options['replace'][0]).update(options['replace'][1])

**Comment by LucasBerbesson** [comment]
```python
field = 'designation'
old_value = 'hello'
new_value = 'bonjour'

Orgue.objects.filter(**{field:old_value}).update(**{field:new_value})

```
