### ISSUE TITLE
[admin] Pouvoir retrouver l'orgue qui utilise une instance jeu d'un certain type de jeu

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/portail#309]
Le formulaire de recherche ci-dessous ne fonctionne pas (erreur 500, je ne suis donc pas fier de mon code) :
https://inventaire-des-orgues.fr/admin/orgues/jeu/

_Nota : Utilité: trouver facilement les orgues qui comporte à type de jeu au nom débile pour correction._

**Comment by LucasBerbesson** [comment]
Oui effectivement, on ne peut pas chercher sur le résultat d'une méthode, il faut remplacer : 
`search_fields = ('nom_du_jeu',)`
par
`search_fields = ('type__nom',)`

Au passage cette page est très lente car pour chaque ligne une requêtes SQL additionnelle est générée pour aller chercher le type, le clavier et l'orgue. Pour l'accélerer il faut ajouter une méthode dans JeuAdmin: 

```
def get_queryset(self, request):
    return super().get_queryset(request).select_related('type','clavier','clavier__orgue')
```

**Comment by LucasBerbesson** [comment]
On peut aussi ajouter des liens directement dans l'admin : 

```python
from django.utils.html import format_html
...
@admin.register(Jeu)
class JeuAdmin(admin.ModelAdmin):
    ...
    def dans_orgue(self, _jeu):
        orgue = _jeu.clavier.orgue
        return format_html('<a href="{}" target="_blank">{}</a>'.format(reverse('orgues:orgue-update',args=(orgue.uuid,)),orgue))

```
