### ISSUE TITLE
Mettre en anglais node, relation et way dans le formulaire pour remplir "type open street map"

### ISSUE THREAD

**Issue by CelestinHuet** [inventaire-des-orgues/portail#316]
Sur OSM, le type du bâtiment est en anglais. Il serait plus simple d'épargner à l'utilisateur une traduction français-anglais. Donc plutôt que mettre noeud, chemin et relation dans le menu déroulant "type open street map" dans le formulaire localisation, il faudrait plutôt node, way et relation.

**Comment by GwilhermPoullennec** [comment]
Oui, une manière élégante de faire est de mettre les deux dans le menu déroulant :
- chemin (way)
- ...
