### ISSUE TITLE
[urls.py] URLs vers édition et création Type_Jeu inexistantes

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/portail#318]
path('types_jeux/creation/', v.TypeJeuCreateJS.as_view(), name='typejeu-create-js'),
    path('types_jeux/edition/<int:pk>/', v.TypeJeuUpdate.as_view(), name='typejeu-update'),

Parce qu'accessibles en modal uniquement ?

**Comment by LucasBerbesson** [comment]
typejeu-update n'est pas utilisée je crois. 
et sinon les vues qui finissent par `-js` ne sont utilisées qu'en javascript ou dans des modales et n'ont donc pas d'url

**Comment by GwilhermPoullennec** [comment]
Maintenant TypeJeuUpdate est utilisée
