### ISSUE TITLE
Signifier (help_text ou autre) que Facteur n'est pas accessible en création à tous

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/portail#321]
C’est fait exprès les premiers mois pour éviter des erreurs dans ces données.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by LucasBerbesson** [comment]
C'est fait, au passage j'ai corrigé un petit bug de permission au niveau de la liste des facteurs (cf mail Matthieu Germain)

**Comment by GwilhermPoullennec** [comment]
Adapter le message pour dire qu’ils sont accessibles mais qu’il faut strictement respecter les conventions de nommage et nous demander en cas de doute.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
