### ISSUE TITLE
Passage à la maille département de la carte d'accueil

### ISSUE THREAD

**Issue by Amaryllis25** [inventaire-des-orgues/portail#322]

**Comment by Amaryllis25** [comment]
A rajouter : requête AJAX
Rajout d'une view ?
Modification de la view déjà créée avec condition ?

**Comment by Amaryllis25** [comment]
#285

**Comment by GwilhermPoullennec** [comment]
On peut regarder cela en démonstration à la prochaine réunion d'équipe.

**Comment by GwilhermPoullennec** [comment]
Amaryllis,
Comment revient-on en arrière une fois que l'on à zoomé à l'intérieur d'une région ?

**Comment by GwilhermPoullennec** [comment]
Les compteurs d'orgue par état (autre que le nombre total donc) restent tous à zéro.

**Comment by Amaryllis25** [comment]
Normalement il faut decliquer sur le département sur lequel on est positionné actuellement.

Amaryllis

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by Amaryllis25** [comment]
Ah c'est ce que je me demandais, je n'ai pas réussi à encore avoir une base de données à jour pour vérifier cela. J'essaierai de l'obtenir demain via l'API, il semble qu'il y ait quelques bugs chez moi pour l'import. Et après cela je chercherai comment corriger les bugs existant.

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by Amaryllis25** [comment]
D'accord je testerai ça ! Merci beaucoup !

**Comment by GwilhermPoullennec** [comment]
Le code javascript update_states doit sûrement pouvoir être factorisé avec update_states2 (en passant "regions" ou "departements" en paramètre...

**Comment by Amaryllis25** [comment]
Suite à un bug, j'attends le réimport de la BDD dans Django pour tester le bouton retour, et le lien OSM. Je mettrai à jour si cela marche.

**Comment by GwilhermPoullennec** [comment]
j'attends le réimport de la BDD dans Django

C’est vous qui faites ?

**Comment by Amaryllis25** [comment]
Non non, je voulais dire que je reimportais le json. Il y a un problème avec les vues de certaines orgues qui ne fonctionnent pas. Mais cela n'a pas réglé le problème, je pense que je vais rentrer des id et relations aléatoires pour faire mes tests pour l'autre ticket en attendant. J'ai quasiment fini de faire le bouton de retour à la maille régionale, je mets ça après avoir fini de manger.

**Comment by GwilhermPoullennec** [comment]
Reste à faire dans la branche dev
- bouton de retour vers la vue régionale à déplacer (éventuellement le faire un peu plus discret)
- ce même bouton ne doit apparaître que sur la vue départementale

**Comment by Amaryllis25** [comment]
Un orgue peut-il être à la fois classé au monument historique et inscrit au monument historique ?

**Comment by GwilhermPoullennec** [comment]
Oui, car ;
- il peut avoir été inscrit puis après classé (plus protecteur)
- il peut avoir le buffet classé et les tuyaux inscrits ou l'inverse. Cependant ce n'est plus le cas pour les inscriptions ou classements récents.
#426

**Comment by Amaryllis25** [comment]
D'accord merci beaucoup ! J'ai une dernière petite question : vous préférez que les orgues inscrits/classés aux monuments historiques soient représentées par un pourcentage ? Ou je laisse juste le nombre brut ?
Par exemple en brut au niveau national : 1522
En pourcentage : 19,03%

**Comment by GwilhermPoullennec** [comment]
Bonne question : par un nombre.
Il faut afficher le nombre sous le nombre d'orgue total, dans un puce en forme de stade et de la couleur "monument historique" (à piocher sur le logo monument historique qui apparaît dans les fiches d'instruments protégés).

**Comment by GwilhermPoullennec** [comment]
#285

**Comment by Amaryllis25** [comment]
D'accord je vais regarder tout ça ! Merci beaucoup !

**Comment by GwilhermPoullennec** [comment]
Toujours sur l'ergonomie de la carte régions/départements 
Il faudrait conserver les statistiques par région, par exemple juste sur survol de la région.
Merci.

**Comment by Amaryllis25** [comment]
Pourrait-on fermer cette issue ? D'autres nouveaux tickets la concerne, et ce qui devait être fait pour celui-ci marche correctement.
