### ISSUE TITLE
Nouveau facteur : deux facteurs sont ajoutés au lieu d'un seul

### ISSUE THREAD

**Issue by CelestinHuet** [inventaire-des-orgues/portail#325]
Dans l'onglet historique, lorsque l'on veut ajouter un nouvel événement avec un facteur qui n'est pas encore répertorié, on peut en créer un nouveau. Mais cela crée deux fois le même au lieu d'un seul.

**Comment by GwilhermPoullennec** [comment]
Célestin, je ne parviens pas à reproduire ce bug.

**Comment by GwilhermPoullennec** [comment]
Célestin, avez-vous pu reproduire ce bug ?

**Comment by CelestinHuet** [comment]
Oui, j'ai ce bug en local et sur le serveur. Sur l'image ci-dessous, je n'ai entré qu'une seule fois le facteur bfdgc et il apparaît deux fois.
![image](https://user-images.githubusercontent.com/79277114/113028348-72f3e400-918b-11eb-91b3-d5c193ee917a.png)

**Comment by GwilhermPoullennec** [comment]
Je ne le reproduit pas, donc c'est peut-être lié aux droits...
A transférer à Lucas...

**Comment by LucasBerbesson** [comment]
Effectivement on peut créer un doublon en double-cliquant sur le bouton "enregistrer". C'est corrigé.

**Comment by GwilhermPoullennec** [comment]
Célestin, quand retesté vous pourrez clore.
