### ISSUE TITLE
Ajouter le logo de la ville de Paris

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/portail#326]
<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by GwilhermPoullennec** [comment]
![Plan-de-travail-36paris-logo](https://user-images.githubusercontent.com/30436457/111168964-d9311200-85a2-11eb-9423-9078304e3392.png)
[Ville_de_Paris_logo_2019_SVG.zip](https://github.com/inventaire-des-orgues/portail/files/6142053/Ville_de_Paris_logo_2019_SVG.zip)


![596px-VILLE_DE_PARIS_LOGO_VERTICAL_POS_RVB](https://user-images.githubusercontent.com/30436457/111168367-4db78100-85a2-11eb-8e52-5293ec14ad8c.png)

**Comment by GwilhermPoullennec** [comment]
Ci-dessus trois formats :
- PNG
- PNG video inverse
- SVG

**Comment by Amaryllis25** [comment]
Voir #335
