### ISSUE TITLE
Notation des octaves graves et aigues

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/portail#329]
ne serait-il pas plus "lisible" de mettre "accouplement 16 Réc./G.O.", avec donc des 4 ou des 16 plutôt que -8 ou +8?

**Comment by patou** [comment]
Je suis d'accord, j'avais pas compris les -8 et +8 en voulant saisir une composition.

**Comment by GwilhermPoullennec** [comment]
C'est fait, la remarque m'aura été souvent remontée !
