### ISSUE TITLE
Logos : ordre et disposition

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/portail#335]
En pied de page, une première ligne, centrée :
- logo Orgue en France, précédé de la mention : "Une initiative"
- logo Ministère de la culture (incluant la mention "Soutenu par" en Myriad Pro
- logo FFAO et logo Ameublement français, précédés par la mention : "Avec le concours de"

Ligne suivante, avec une même hauteur pour les logos, plus petite que la hauteur des logos de la première ligne, groupe de logos centré :
- logo région Bretagne
- logo région Bourgogne
- logo région Centre

Ligne suivante, groupe de logos centrés :
- logo Orgue en Pays de la Loire
- logo ADORA Aquitaine

**Comment by Amaryllis25** [comment]
Doit-on enlever le logo de l'inventaire National des Orgues ?

**Comment by Amaryllis25** [comment]
![image](https://user-images.githubusercontent.com/79219571/111997654-8c59b800-8b1b-11eb-9ebc-fae6cd6b0343.png)

**Comment by GwilhermPoullennec** [comment]
Il n’est pas obligatoire de remettre le logo de l’inventaire dans le pied de page.

**Comment by Amaryllis25** [comment]
#326

**Comment by Amaryllis25** [comment]
Ou devrait aller le logo de la ville de Paris?

**Comment by GwilhermPoullennec** [comment]
Je ne sais pas trop.
 Avec les régions pour l’instant...

**Comment by Amaryllis25** [comment]
![image](https://user-images.githubusercontent.com/79219571/112316982-e4bfbf80-8cab-11eb-82cf-298d56ae434b.png)
Orgue de France Myriad Pro inclut

**Comment by GwilhermPoullennec** [comment]
Ha, excellent, ce sera plus "classe". Un petit peu plus d'espace entre Une initiative... et le logo lui-même et ce sera parfait. Merci !

**Comment by Amaryllis25** [comment]
Oui c'est ce que je faisais justement en regardant l'image ! Je suis en train de rajouter l'espace, et après j'en fait de même pour les deux images restantes.

**Comment by Amaryllis25** [comment]
![image](https://user-images.githubusercontent.com/79219571/112318284-28ff8f80-8cad-11eb-8faf-cf1de12ddb5b.png)

**Comment by GwilhermPoullennec** [comment]
Classe.
Si vous avez un fichier source en format autre que .jpg, n'hésitez pas à nous l'envoyer à part, pour éviter de tout recontruire en cas de modification.
Il faudrait d'ailleurs que je déverse tous les fichiers sources de logo dans un coin du dépôt.

**Comment by Amaryllis25** [comment]
Du coup il faut que je vous envoie tous les logos ? Je comptais les mettre dans la branche développement

**Comment by GwilhermPoullennec** [comment]
Le fichiers sources des logo (genre .psp ou .svg) peuvent effectivement être mis dans la branche développement, dans un répertoire qui va bien, isolé de Django éventuellement.

**Comment by Amaryllis25** [comment]
D'accord je ferai ça quand j'aurai terminé !

**Comment by Amaryllis25** [comment]
![image](https://user-images.githubusercontent.com/79219571/112334843-088b0180-8cbc-11eb-9e03-ac905b7bf8a7.png)

**Comment by Amaryllis25** [comment]
![logo_adora](https://user-images.githubusercontent.com/79219571/112335996-fa89b080-8cbc-11eb-9495-4a1293d28af2.png)
Avec logo aplanit

**Comment by Amaryllis25** [comment]
![image](https://user-images.githubusercontent.com/79219571/112336095-0ecdad80-8cbd-11eb-89c3-da017e9fb3e4.png)

**Comment by GwilhermPoullennec** [comment]
Cool.
C’est le problème récurrent des logos non vectoriels...

**Comment by Amaryllis25** [comment]
D'accord ! Je vais voir une méthode "plus propre" pour centrer les logos comme je l'ai fais (à moins qu'Eliott veuille le faire) #275

**Comment by Amaryllis25** [comment]
J'ai créé une nouvelle branche, comme cela n'est pas du code propre, le temps qu'Elliott le modifie. On pourra faire un merge sur la branche dev lorsque le code sera parfait ! A toi de jouer Elliott ;)
En fait il faudrait enlever les propriétés margin et display et utiliser text-center du bookscrap d'on à parle M. Berbesson, je pense que c'est le plus simple ? A toi de voir.
PS : Dis-moi s'il y a pas de problèmes avec les images, j'ai normalement tout mis à jour dans le dossier img de la branche dev, mais je ne suis pas à l'abri d'un oubli :)

M. Poullennec il faudrait peut-être fermer la branche #275 pour éviter les duplicatas, tout en laissant un retour à celle-ci sur cette issue, qu'en pensez-vous ?

**Comment by Amaryllis25** [comment]
J'ai réactualisé les logos de la Bretagne et d'Orgue en Pays de la Loire, dites-moi si cela marche à présent.

**Comment by GwilhermPoullennec** [comment]
OK. Merci ! Si on doit peaufiner, on le fera dans la branche dev.
Donc je fusionne Footer dans master et supprime Footer.

**Comment by Amaryllis25** [comment]
D'accord pas de problème !

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________
