### ISSUE TITLE
Logos Ajout logo ADORA

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/portail#340]
![logo_170_o](https://user-images.githubusercontent.com/30436457/111181643-79d8ff00-85ae-11eb-8ec0-f1b1b1ee41da.png)

**Comment by GwilhermPoullennec** [comment]
Il faut probablement aplanir le fond de couleur de ce logo pour éviter l'effet relief

**Comment by GwilhermPoullennec** [comment]
#335

**Comment by Amaryllis25** [comment]
Demande à des amis pro en photoshop pour l'effet de relief
Rajout d'ici demain soir
