### ISSUE TITLE
Ajouter le numéro du département dans la liste des départements

### ISSUE THREAD

**Issue by patou** [inventaire-des-orgues/portail#362]
On ne connait pas forcement les noms des départements, cela serait intéressant d'ajouter en début ou fin de la liste des département le numéro du département.

01 Ain
02 Aine
...
75 Paris
...

**Comment by GwilhermPoullennec** [comment]
Probablement moins joli, mais si la recherche a lieu sur le nom de département il faudra privilégier la disposition suivante 
- Ain (01)
- Aisne (02)
...

**Comment by patou** [comment]
Les chiffres avant permettent d'avoir un meilleur alignement du texte.
Pour la recherche si le champs select utilise le composant select2 comme dans la saisie d'orgue, la recherche pourra alors se faire sur le numéro de département ou le nom du département.

**Comment by LucasBerbesson** [comment]
Le code du département n'est plus dans le formulaire, il s'enregistre automatiquement en arrière-plan, ça devrait régler le pbm.

**Comment by patou** [comment]
> Le code du département n'est plus dans le formulaire, il s'enregistre automatiquement en arrière-plan, ça devrait régler le pbm.

En fait ma suggestion était plutôt sur le formulaire de recherche sur la page d'accueil.
