### ISSUE TITLE
Afficher un lien vers les orgues d'un même lieu

### ISSUE THREAD

**Issue by patou** [inventaire-des-orgues/portail#363]
Lorsque l'on est sur une fiche, avoir des liens permettant de naviguer vers d'autres orgues.

Par exemple : 
- Si on est sur l'orgue de tribune, afficher le liens vers l'orgue de choeur dans le même lieu.
- Avoir un lien pour voir les orgues de la même ville.
- Permettre de voir les orgues d'un même facteur d'orgue ...

**Comment by GwilhermPoullennec** [comment]
Permettre de voir les orgues d'un même facteur d'orgue ...
-> Déjà possible via la recherche, je pense que cela devrait suffire.

**Comment by GwilhermPoullennec** [comment]
- Si on est sur l'orgue de tribune, afficher le liens vers l'orgue de choeur dans le même lieu.
- Avoir un lien pour voir les orgues de la même ville.

> A quel endroit proposez-vous de disposer ce lien ?

**Comment by patou** [comment]
> Permettre de voir les orgues d'un même facteur d'orgue ...
> -> Déjà possible via la recherche, je pense que cela devrait suffire.

Justement juste transformer les champs qui peuvent faire l'objet d'une recherche par un lien lançant la recherche. (Facteur, ville, département).

Cela permet de naviguer entre les orgues, mais ça permettra aussi d'augmenter le référencement du site.
