### ISSUE TITLE
Effacer le style dans les champs enrichis

### ISSUE THREAD

**Issue by patou** [inventaire-des-orgues/portail#365]
Lorsque l'on copie tu texte depuis un autre site, le style de ce site est copié également.
Il n'y a pas moyen d'effacer le style du texte dans ce champ.
On se retrouve donc avec du texte qui n'a pas le même style que le reste de la page : 
<img width="656" alt="Capture d’écran 2021-03-21 à 10 45 16" src="https://user-images.githubusercontent.com/841858/111900378-994eac80-8a32-11eb-95b2-ba43af68d636.png">

**Comment by patou** [comment]
Peut être utiliser le plugin clean paste : 
https://alex-d.github.io/Trumbowyg/documentation/plugins/#plugin-cleanpaste

Si des gens font des copiers coller de words ça va vite compliquer les choses.

**Comment by LucasBerbesson** [comment]
Merci on va déjà tester https://alex-d.github.io/Trumbowyg/documentation/#remove-format-pasted, c'est dans un commit que je vais bientôt push

**Comment by LucasBerbesson** [comment]
voilà c'est en ligne :)
