### ISSUE TITLE
[édition] Le champ references_palissy doit être vérouillé

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/portail#368]
Permissions particulières ou bien même permission que les champs commune, etc.

**Comment by LucasBerbesson** [comment]
Le plus simple serait de déplacer `references_palissy` vers la page "Localisation" qui a déjà des permissions spéciales. Quitte à modifier le nom de cette page en "Champs spéciaux" à l'avenir.
