### ISSUE TITLE
Ajout lien vers OSM lorsque type d'objet et id objet OSM sont présents

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/portail#370]
Lien sous la forme 
https://www.openstreetmap.org/relation/150879

A mettre juste sous la mini-carte OSM en bas du cartouche de résumé ?

**Comment by Amaryllis25** [comment]
Je pense qu'il faut envoyer une requête ajax quand on est sur l'ogue en question, et s'il l'id et la relation n'est pas "null", alors on affiche le lien ? Qu'en pensez-vous ?

**Comment by GwilhermPoullennec** [comment]
Au préalable essayer directement dans le template de mettre une condition (cf. Plans sonores et autres exemples).

**Comment by Amaryllis25** [comment]
Oui c'est ce que je vais faire ! J'ai posé une question dessus à M. Berbesson justement. Du coup ça devrait être rapide. J'essaie de récupérer correctement le nouvelle BDD pour le faire.

**Comment by GwilhermPoullennec** [comment]
Vous pouvez faire un essai sur un orgue en local en ayant mis un type_osm et id_osm

**Comment by Amaryllis25** [comment]
Alors tout à l'air de fonctionner, je vais mettre à jour le code ! J'ai rentré des id aléatoires ou non, et de vrais id sur certaines cathédrales/églises pour voir si les liens qui se faisaient étaient bien corrects. Je mets ça à jour d'ici 5 minutes.

**Comment by Amaryllis25** [comment]
Je mets ça directement sur la branche dev ou je créé une nouvelle branche pour ça ?

**Comment by GwilhermPoullennec** [comment]
Ca marche, merci !
On pourrait sûrement trouver un nom plus grand public pour le lien, à réfléchir.

**Comment by GwilhermPoullennec** [comment]
J'ai modifié les noms de liens
Et tout mis en template pur (sans javascript).
