### ISSUE TITLE
Etendue : notation du ravalement F0

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/portail#371]

**Comment by GwilhermPoullennec** [comment]
Documentation mise à jour en attendant mieux.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by patou** [comment]
Et c'est quoi les ravalements que tu veux mettre dans l'étendu ?

**Comment by GwilhermPoullennec** [comment]
Il y en a plein de types différents, c’est bien là le problème...

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by patou** [comment]
> Il y en a plein de types différents, c’est bien là le problème...
> 
> <sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

J'ai mal posé ma question, c'est quoi les ravalements ?

**Comment by GwilhermPoullennec** [comment]
Pardon ! C'est le fait, dans les orgues anciens avec peu ou pas de jeux graves, de descendre pour quelques tuyaux (et éventuellement jeux) en-dessous de la tessiture normales des claviers. Contre-la, contre-fa, etc.

**Comment by patou** [comment]
> Pardon ! C'est le fait, dans les orgues anciens avec peu ou pas de jeux graves, de descendre pour quelques tuyaux (et éventuellement jeux) en-dessous de la tessiture normales des claviers. Contre-la, contre-fa, etc.

Mais du coup, c'est tous le clavier qui a des notes supplémentaire ?

Pourquoi c'est compliqué de mettre F0-C3 ?

**Comment by GwilhermPoullennec** [comment]
Parce que c'est souvent "à trous", le ravalement ne valant que pour les notes les plus utilisées (par exemple F, C, D, ou encore les naturelles mais pas les dièses, etc.)
Un truc d'organiste, quoi.

**Comment by GwilhermPoullennec** [comment]
Oui, c'est l'usage adopté par certains et que l'on pourrait poser comme convention.
Si tu as le courage de mettre à jour l'expression régulière...

**Comment by patou** [comment]
J'ai développé dans la MR sur le calcule du nombre de notes d'un clavier, la solution pour noter les ravalements,
Ce que je propose, c'est de lister toutes les notes avant le première interval, exemples : 
- CD1-G5 : Pour pas de do#
- CFDGEAA#BC1-G5 : Pour l'octave courte italienne Do Fa **Ré** Sol **Mi** La **Sib** Si Do
- F0-G5 : Si il y a toutes les notes de Fa à Do
- A0-C8 : L'étendue d'un piano (88 notes)

**Comment by patou** [comment]
> J'ai développé dans la MR sur le calcule du nombre de notes d'un clavier, la solution pour noter les ravalements,
> Ce que je propose, c'est de lister toutes les notes avant le première interval, exemples :
> 
> * CD1-G5 : Pour pas de do#
> * CFDGEAA#BC1-G5 : Pour l'octave courte italienne Do Fa **Ré** Sol **Mi** La **Sib** Si Do
> * F0-G5 : Si il y a toutes les notes de Fa à Do
> * A0-C8 : L'étendue d'un piano (88 notes)

Et j'ai même rajouté le fait d'accepter les bémoles, on peut donc écrire l'octave courte : CFDGEAB♭BC1-C1 ou C1-D♭3
Et je valide aussi que l'intervalle n'est pas inversé C5-C1, ou compris entre 5 et 88 notes. ( je sais pas quel est le minimum pour la taille d'un clavier)

**Comment by patou** [comment]
Et les modifications que j'ai fait pour le nombre de notes par clavier ont implémenter tous les types de ravalements...
Je pense que l'on peut fermer cette issue

**Comment by GwilhermPoullennec** [comment]
Exact.
