### ISSUE TITLE
Question orgue_detail

### ISSUE THREAD

**Issue by Amaryllis25** [inventaire-des-orgues/portail#372]
Bonjour M. Berbesson,

Je suis en train d'explorer le fichier orgue_detail.html à la suite d'une requete de M. Poullennec. J'aimerais savoir si vous pouviez m'expliquer cette écriture:
![image](https://user-images.githubusercontent.com/79219571/112010489-a7322980-8b27-11eb-9e0c-44f25791dd95.png)

En fait il y a plein de conditions de ce type avec des %, et je n'ai jamais vu ça. Par exemple si je veux vérifier qu'il y a bien un id et une relation OSM, je peux écrire :
              {% if orgue.osm_type and orgue.id %}
                <div>Ce que je dois faire</div>
              {% endif %} ?

**Comment by LucasBerbesson** [comment]
Bonjour, pour comprendre de quoi il s'agit il faut lire la [documentation de django ](https://docs.djangoproject.com/fr/3.1/ref/templates/language/). Tout y est très bien expliqué. 

à partir du moment ou l'instance `orgue` est disponible, on peut appeler toutes les propriétés du modèle `Orgue`. 
Par exemple : 
```django
{{ orgue.commune }}
{{ orgue.code_insee }}
{{ orgue.ancienne_commune }}
{{ orgue.departement }}
{{ orgue.code_departement }}
{{ orgue.region }}
{{ orgue.latitude }}
{{ orgue.longitude }}
{{ orgue.osm_type }}
```
 ou encore 
```
{% if orgue.osm_type and orgue.id %}
<p>{{orgue.osm_type}}</p>
{% endif %} 
```

Par contre la condition `{% if orgue.id %}` est un pléonasme car à partir du moment ou un orgue existe, il a forcément un id

**Comment by Amaryllis25** [comment]
Ah pardon je voulais dire orgue.id_osm, je n'avais pas vu que j'avais oublié un bout de la caractéristique.
D'accord en fait c'est très puissant ! Du coup je vois quoi faire merci beaucoup ! Je vais aller relire la documentation ça ne me fera pas de mal.
Bonne après-midi !
