### ISSUE TITLE
[SEO] sitemap

### ISSUE THREAD

**Issue by patou** [inventaire-des-orgues/portail#379]
Pour permettre au moteur de recherche d'indexer les orgues, il est nécessaire d'avoir des pages qui listes les orgues et qui les affichent en html.

**Comment by LucasBerbesson** [comment]
cf https://docs.djangoproject.com/fr/3.1/ref/contrib/sitemaps/

**Comment by LucasBerbesson** [comment]
Il faudra aussi retirer le robots.txt pour autoriser l'indexation par les moteurs de recherche
