### ISSUE TITLE
Console

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/portail#38]
Ne pas parler de console : Buffet/Console peut s'intituler simplement Buffet.

**Comment by LucasBerbesson** [comment]
L'onglet d'édition "Buffet" ne comportera qu'un seul champ, on le maintient quand même ?

**Comment by GwilhermPoullennec** [comment]
Discussion avec le président des facteurs d'orgues : on garde Buffet / console.
