### ISSUE TITLE
Ajouter Numérique pour les transmissions des notes et tirage des jeux

### ISSUE THREAD

**Issue by patou** [inventaire-des-orgues/portail#380]
Il faudrait ajouter dans la liste des transmissions des notes et des tirage des jeux l'option Informatique.

C'est différent de l'option Electrique dans le sens que cela va encoder un signal midi (donc informatique)

C'est une option qui est dans l'inventaire des pays de la loire.
Mais je sais que l'orgue de la veille église de Puteaux est dans ce cas, la console dialogue en midi avec la tribune pour les notes et les jeux.

**Comment by GwilhermPoullennec** [comment]
On se posait la question avec OPL si « numérique » ne serait pas mieux : c’est le vecteur. MIDI est une norme.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by patou** [comment]
Oui numérique, pourquoi pas.
C'est juste qu'il faut faire la différence avec électrique qui va avoir un fil par note alors que le numérique va encoder un message qui va transiter dans un seul câble qui sera décodé ensuite.

**Comment by GwilhermPoullennec** [comment]
Ok
