### ISSUE TITLE
[Carte] Remplacer leaflet par mapbox

### ISSUE THREAD

**Issue by LucasBerbesson** [inventaire-des-orgues/portail#381]
Il faut remplacer leaflet par [mapbox](https://www.mapbox.com/) en mode gratuit (jusqu'à 50 000 affichages par mois). 
Cela devrait permettre notamment de changer plus facilement les informations affichées en fonction du niveau de zoom et d'ajouter des filtres.

**Comment by Amaryllis25** [comment]
J'ai déjà un compte mapbox, quasiment inutilisé (je l'ai utilisé pour mes cours), je peux mettre à jour la carte avec mapbox, mais il faudra peut-être changer la clé d'accès avec un compte mapbox uniquement dédié à l'affichage des orgues pour éviter des dédoublements d'utilisation de la carte (avant que celle-ci soit rajouter à la branche master).

**Comment by Amaryllis25** [comment]
Pour la création d'un compte mapbox : https://account.mapbox.com/
Donnez-moi la clé d'accès qui vous sera fourni, ainsi je la mettrai et pousserai le changement sur la branche dev
