### ISSUE TITLE
Facteurs : symbole sur la carte (Leaflet ou Mapbox)

### ISSUE THREAD

**Issue by CelestinHuet** [inventaire-des-orgues/portail#382]
Quel doit être le style des marqueurs représentant une manufacture d'orgue sur la carte Leaflet ?

**Comment by GwilhermPoullennec** [comment]
![icone facteurs d'orgues_Plan de travail 1](https://user-images.githubusercontent.com/30436457/112964121-52566a80-9148-11eb-8e72-f4d3b7a83685.png)
![icone facteurs d'orgues_Plan de travail 2_Plan de travail 1](https://user-images.githubusercontent.com/30436457/112964123-52ef0100-9148-11eb-9066-ce2ac71a6be8.jpg)

**Comment by patou** [comment]
Je pas très fan de cette icon, on a du mal à comprendre...
Déjà il faudrait la tourner pour que la pointe de l'accordeur doit bien le point d'encrage.
![image](https://user-images.githubusercontent.com/841858/114270417-7b121600-9a0c-11eb-8da1-47ff2abb520d.png)
Le point d'encrage est en bas au milieu de l'image, alors que la point nous montre le coin inférieur gauche.
L'ombre est toujours dirigé vers le point d'encrage habituel.

Personnellement, j'aurais mis un marker d'une autre couleur.
(Et ajouter une légende à côté).
