### ISSUE TITLE
Pouvoir exporter la config depuis le site

### ISSUE THREAD

**Issue by patou** [inventaire-des-orgues/portail#384]
Le script init_config permet d'initialiser la config sur l'environnement en local (jeux, facteurs, etc..).
Or ces configurations peuvent être modifié sur le site. Il faudrait une option pour pouvoir exporter la config depuis le serveur pour ensuite l'importer dans notre environnement local.

**Comment by GwilhermPoullennec** [comment]
Script manage.py create_config

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by patou** [comment]
Il faut l'exécuter côté serveur ?
Cela ne pourrai pas être disponible via l'API ?

**Comment by patou** [comment]
> Script manage.py create_config
> 
> <sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

J'ai pas trouvé de script create_config.py

**Comment by GwilhermPoullennec** [comment]
Oui, il faut le créer.

**Comment by GwilhermPoullennec** [comment]
En fait plus simplement cela doit être faisable directement 
un lien qui renvoie le config.json

**Comment by GwilhermPoullennec** [comment]
https://inventaire-des-orgues.fr/api/v1/config.json
