### ISSUE TITLE
Historique des contributeurs

### ISSUE THREAD

**Issue by patou** [inventaire-des-orgues/portail#389]
L'idée est de garder seulement la dernière version d'une fiche d'orgue.
Mais il peut être intéressant de garder la liste de toutes les contributeurs d'une fiche.
Car si une personne vandalise une fiche et que quelqu'un s'en rend compte et commence à modifier la page pour rétablir, alors on ne verra plus quel était la personne qui a vandalisé la fiche.
De plus il peut être intéressant de savoir la liste complète des personnes qui ont contribué à un orgue, cela permet de mettre en valeur tous les contributeurs et d'afficher le nombre de modification.
On pourrait avoir une liste qui reprend : 

- Date de modification
- Utilisateur
- Section modifié (Information générale, Composition, Photo, Sources, ...)

Dans l'administration, il y a déjà un système avec l'historique des modifications, mais il n'est pas renseigné via les formulaires sur le site.
Sinon, un plugin permet de le faire de manière plus complète, en gardant l'historique de toutes les modifications et permettant d'avoir un diff des changements et restaurer une ancienne version (plus simple que de prendre une sauvegarde de la base)
https://github.com/jazzband/django-simple-history 
Cela permet d'avoir une vrai gestion comme dans un wiki, mais avec beaucoup plus de donnés enregistrés.

Lors de la présentation, c'était une grande crainte ressentie par les participants. Un simple historique des contributeurs sera à même de les rassurer.

**Comment by GwilhermPoullennec** [comment]
Effectivement cette demande revient souvent.
Lucas considère l'historique complet assez lourd, complexe et peu sobre pour un gain assez faible.
Peut-être une simple liste des contributeurs serait déjà largement suffisante.

Surtout on regarde commennt évoluent les fiches en pratique. Je pense que pour les premiers mois, dans 98% des cas, il n'y a qu'un contributeur par fiche de toute manière.

L'expérience de Bastien et Lucas est que les utilisateurs ont souvent cette crainte mais en pratique les problèmes sont très rares et se traitent à la marge.

**Comment by patou** [comment]
Je suis d'accord qu'une simple liste peut suffire.
Comme c'est souvent une crainte, de le mettre en place, sera pourra réduire cette crainte.

De plus en tant que contributeur, je suis aussi fière que mon nom reste sur les orgues auquel j'ai contribués. (qui peut être remplacer par une personne qui va juste corriger une typo...)

**Comment by GwilhermPoullennec** [comment]
Effectivement, on peut partir sur cette solution raisonnable d'une liste, par exemple les quatre derniers contributeurs. En pratiquen, dans 99,9% des cas, nous aurons ainsi tous les contributeurs.

**Comment by patou** [comment]
C'est pas dit pour 4 contributeurs, car à chaque fois qu'on modifie une section, on fait une modification.

**Comment by patou** [comment]
Je suis également partant pour développer cet partie.

**Comment by patou** [comment]
> Je suis également partant pour développer cet partie.

je commence à bosser sur cette fonctionnalité

**Comment by patou** [comment]
Je propose de regrouper les contributions si on fait plusieurs modification le même jour (sans autres modifications par une autre personne).
![image](https://user-images.githubusercontent.com/841858/116060000-bf92e800-a681-11eb-871c-21852a202314.png)
Plutôt que d'avoir une contribution pour chaque modifications : 
![image](https://user-images.githubusercontent.com/841858/116060162-e94c0f00-a681-11eb-81f8-f39060c2e910.png)

**Comment by patou** [comment]
L'historique des contributions est prêt à être revue dans les pull request.
N'hésitez pas à faire des commentaires en particulier les descriptions a mettre sur chaque parties.
