### ISSUE TITLE
Gestion du cadrage des vignettes comme les autres images sur disque ou en BD, hors du dossier CACHE

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/portail#392]
Cf. #250

**Comment by LucasBerbesson** [comment]
C'est bon les vignettes "recadrées" sont enregistrées aux emplacements : 
```
/media/code_departement/code_orgue/images/vignette.jpg
```
le `CACHE` contient uniquement des miniatures automatiquement générées au format 600x450 à partir d'images originales chargées par les utilisateurs. Il ne sert qu'à réduire le temps de chargement quand on affiche beaucoup d'images d'un coup (par exemple en base de la fiche d'un orgue)
