### ISSUE TITLE
Filtrage temporel des orgues

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/portail#4]
Pouvoir rechercher sur le temps :
    - un intervalle de dates saisies par l'utilisateur, la seconde étant initiée à la première + 30 ans
    - ou un intervalle -15ans + 15ans autour d'une date saisie par l'utilisateur

**Comment by LucasBerbesson** [comment]
J'ai ajouté la possibilité de chercher par facteur. Par contre pour le temps je pense que la recherche ne va pas être très fiable, surtout si un orgue a plusieurs évènements étalés sur une longue période ...

**Comment by GwilhermPoullennec** [comment]
Oui, on repousse l'histoire de la recherche sur le temps à une version ultérieure.
