### ISSUE TITLE
Erreur 403 sur l'export CSV

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/portail#412]

**Comment by LucasBerbesson** [comment]
Maintenant il y a une erreur 500 car il manque une `permission_required` dans les attributs de la classe.   
Est-ce que n'importe qui peut faire cet export ?

**Comment by GwilhermPoullennec** [comment]
#263

**Comment by GwilhermPoullennec** [comment]
Oui, on peut donner en accès à tous, c'est pour cela que je n'avais pas spécifié de permission (je croyais que dans les classes mères au-dessus de celles Fabdev il y avait un permission_required = None par défaut, j'ai dû zapper quelque chose).

En attendant j'ai mis permission orgue.change_orgue

**Comment by LucasBerbesson** [comment]
Oui en fait `fabutils.mixins.FabView` oblige à avoir une permission.   
Sinon il faut utiliser `django.views.generic.View`
