### ISSUE TITLE
Ajouter les numéros IM

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/portail#413]

**Comment by GwilhermPoullennec** [comment]
Faire comme le champ references_palissy
L'ajouter aux formulaires

Nom du nouveau champ : references_inventaire_regions

**Comment by Amaryllis25** [comment]
![image](https://user-images.githubusercontent.com/79219571/115511056-b5877880-a280-11eb-9364-adcef731fdbd.png)

**Comment by Amaryllis25** [comment]
J'ajoute ce nouveau champ dans les informations générales ?

**Comment by Amaryllis25** [comment]
![image](https://user-images.githubusercontent.com/79219571/115515666-a9ea8080-a285-11eb-9b39-71090c33b58b.png)

**Comment by GwilhermPoullennec** [comment]
Très bien.
Disposer ce champ juste après le champ Palissy.

**Comment by GwilhermPoullennec** [comment]
Amarylis, avez déposé le code correspondant sur la branche dev ? Merci.

**Comment by Amaryllis25** [comment]
Bonjour Monsieur Poullennec,

Non je ne l'ai pas déposé pour le moment, je ferai ça demain, je suis occupée aujourd'hui.

Bonne journée,

Amaryllis Vignaud

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by Amaryllis25** [comment]
Ne devait-il pas y avoir une contrainte pour que le champ soit uniquement modifiable par les admins ? Si oui comment faire, sinon cela est-il automatique ?

**Comment by GwilhermPoullennec** [comment]
Ajouter des permissions dans views 
Faire une recherche sur « references_palissy »
et faire de même !

**Comment by Amaryllis25** [comment]
Normalement tout est bon.
