### ISSUE TITLE
Ajout et modification de jeux

### ISSUE THREAD

**Issue by patou** [inventaire-des-orgues/portail#420]
# Jeux

Voici les jeux trouvé dans l'import des orgues des pays de la loire qui n'existe pas dans la liste des jeux.
Plusieurs jeux non pas la bonne hauteur
Des fautes d'orthographe ? Comment corrige ton les erreurs ?

- Bourdon conique	8
- Bourdon flûte 8
- Bomarde (Bombarde ?)
- Carillon I-III
- Carillon II-IV
- Chamade 4 (hauteur 4/8)
- Chromhorne 8
- Cimbale III (hauteur II)
- Cimbel III
- Clairon - Hautbois 4 (hauteur 4/8)
- Contre-basse (existe Contrebasse)
- Cornet II-III
- Cornet I-III
- Cornettino III
- Corno Inglese 16
- Cromorne 4
- Cymbale V-VI
- Doublete (Doublette ?)
- Dulcian 8 (hauteur 32)
- Feldtrompete 4
- Flageolet 8 (hauteur 4, 2, 1)
- Flagolet 2
- Fluit 4 (existe Roerfluit, Quintfluit, Open fluit, Spitsfluit)
- Fluste 8 (transformer en Flûte ?)
- Fluste à neuf trous 2 (ou écrire 9 trous ?)
- Fluste Bouchez (transformer en Flûte Bouchée ?)
- Fluste d'allemand (transformer en Flûte d'Allemand ?)
- Flûte à cheminées (transformer en Flûte à cheminée ?)
- Flûte large 4
- Flûte ouvert 8 (transformer en Flûte ouverte ?)
- Flutebasse 8 (transformer en Flûte basse ?)
- Fourniture VII (existe dans d'autres nombres rangs ou appellation)
- Fournitures III (Remplacer en Fourniture ?)
- Fugara 8 (hauteur 4)
- Gedeckt 8 (existe Doppel Gedeckt et Gedecktbass)
- Gemshorm 4 (remplacer par Gemshorn ?)
- Grande fourniture II-IV
- Grande tierce 1 3/5
- Grosse flûte bouchée 16
- Grosse fourniture II-IV
- Haut-bois 8 (remplacer par Hautbois ?)
- Basson-hautbois 8 (hauteur en 4)
- Hintersatz IV
- Holzdulzian 16
- Koraal-bas 4
- Mixture IV-V
- Mixture II-IIIs
- Nachthorn 2 (dans la base avec le 2 dans le nom et la hauteur vide)
- Nasart 2 2/3
- Nasat 2 2/3
- Octavbasse 8 (remplacer par Octavbass ou Octavebasse?)
- Octave-Quinte
- Octavin harmonique
- Oktave 4 (existe Oktav 4)
- Oktave 2 (existe Superoktav)
- Petit cornet IV
- Petite Chalemie 4
- Plain jeu IV (remplacer par Plein-jeu ?)
- Plain jeu V (remplacer par Plein-jeu ?)
- Plein-jeu 16' I (il faut mettre Plein-jeu I  qui n'existe pas non plus ?)
- Plein-jeu II
- Plein-jeu II-V
- Plein-jeu I-IV
- Prinicpal 8 (remplacer par Principal 8 ?)
- Quintaden 8 (remplacer par Quintadena ?)
- Quintaden 4 (remplacer par Quintadena ?)
- Quintadene 8 (remplacer par Quintadena ?)
- Quinte 3 (existe Quinte Flûte 3)
- Quintelette 1 1/3 (remplacer par Quinte ?)
- Quintflöte 1 1/3
- Sacqueboute 8
- Sacqueboute 16
- Salcional 8 (Remplacer par salicional ?)
- Salitional 8 (remplacer par salitional ?)
- Scharf III (existe hauteur 3 rgs)
- Scharff III (existe Scharf 3 rgs)
- Sesquilatera II (hauteur II-III)
- Soubase 16 (remplacer par Soubasse ?)
- Soubasse acoustique 32 (existe Soubasse)
- Sous-basse 8 (remplacer par Sousbasse ?)
- Spitzflöte 8 (hauteur 4)
- Spitzflöte 2 (hauteur 2)
- Subbas 16 (remplacer par Subbass 16 ?)
- Tercian II
- Tierce 8 (je sais pas si ça existe ???)
- Tierce 2 (je sais pas si ça existe ???)
- Tiercyne 1 3/5
- Tremblant (mettre dans les accessoires ?)
- Trommete 8 (remplacer par Trompete ?)
- Trompete royale 8
- Trompette royale 4
- Trompette de chamade 8 (remplacer par Trompette en chamade ?)
- Trompette chamade 8 (remplacer par Trompette en chamade ?)
- Tuba harmonique 8 (existe Tuba 8)
- Unda Maris 4 (hauteur 8)
- Viola 4 (hauteur 8)
- Viola da Gamba 8 (remplacer par Viola di Gamba ?)
- Viola de Gamba 8 (remplacer par Viola di Gamba ?)
- Wald Flute 4 (pas de WaldFlöte ou WaldFlûte)

**Comment by patou** [comment]
Le fichier csv à remplir est ici : https://github.com/inventaire-des-orgues/paillasse/blob/7e8ab3b031aa2eda117dacabcde009e1ce50aefc/paysdelaloire/data/jeux.csv

**Comment by patou** [comment]
J'ai remplis aussi l'orgue de Saint Pasquier à Nantes, et j'ai une interrogation.
https://inventaire-des-orgues.fr/detail/orgue-nantes-eglise-saint-pasquier-fr-44109-nante-stpasq1-x/
Il y a un jeu Cornet sur le Grand Orgue, mais en faire c'est un appel Cornet (il ouvre la montre 9, le prestant 4, la double 2, le nazard 2 2/3 et la tierce 1 1/3).
Pour moi c'est à mettre comme un jeu propre, et non comme un accessoire ?

**Comment by GwilhermPoullennec** [comment]
Héhé, effectivement, c'est un cas amusant. C'un orgue à tirage de jeux pneumatique ou électropneumatique j'imagine (je ne l'ai jamais joué !).
Je dirai oui en réponse à ta question, (c'est une forme d'emprunt), mais c'est discutable et on pourrait tout à fait dire qu'il s'agit d'une combinaison.
La question de fond est : parle-t-on des registres à la console ou des vrais registres ? Or, on note les jeux empruntés, visibles à la console, alors que ce ne sont pas de vrais registres indépendants, d'où ma réponse.

Par ailleurs, je dirai qu'il s'agit là typiquement d'une information à glisser dans le résumé, ce qui fait la spécificité de l'orgue;

**Comment by patou** [comment]
Tu as ajouté tout ces jeux ?

**Comment by GwilhermPoullennec** [comment]
J’ai complété le CSV, créé la plupart des jeux.
Certains ne sont pas créés mais si le script gère la création nous aurons tout.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by patou** [comment]
> J’ai complété le CSV, créé la plupart des jeux.
> Certains ne sont pas créés mais si le script gère la création nous aurons tout.
> 
> Sent with [GitHawk](http://githawk.com)

Ok super, j'étais aussi en train de compléter le CSV.
Si tu met un None dans le CSV, il n'est pas ajouté.
Si tu met une valeur, ça utilisera cette valeur.
