### ISSUE TITLE
Ajout d'accessoires

### ISSUE THREAD

**Issue by patou** [inventaire-des-orgues/portail#421]
# Accessoires

Voici la liste des accessoires manquant que j'ai dans l'import des orgues des pays de la Loire

- 2 combinaisons libres
- 5 combinaisons ajustables
- appel registration
(On remplace par Combinaisons libres ?)

---------------

- combinaison fixe : grand choeur
- combinaison fixe : hautbois
- combinaison fixe : jeux de fonds
- combinaison fixe : voix celeste
- combinaison fixe : voix humaine
- 4 combinaisons fixes
- 5 combinaisons fixes
(Pas d'option pour les combinaisons fixes)

---------------

- anches (pas de clavier précisé)
- appel-renvoi anches
- appel anches
- Anches Ech.
- Anches G.Ch. (Grand Choeur)

---------------

- Annulateur anches
- Annulateur anches grand-orgue
- Annulateur anches positif
- Annulateur anches pedale
- Annulateur anches recit
- Annulateur mixtures grand-orgue
- Annulateur mixtures positif
- Annulateur mixtures recit
- Annulateur recit 8
- renvoi anches grand-orgue
- renvoi general
- retrait anches
- retrait anches recit
(Pas d'accessoire pour annuler ou renvoyer)

---------------

- appel / retrait trompette 8
- appel bourdon
- appel chamade
- appel clairon
- appel cornet
- appel cornet positif
- appel prestant
- appel principal 16 pedale
- appel-retrait bombarde
- appel-retrait chamade
- appel/renvoi trompette
(Pour les appels vers un jeu particulier)

---------------

- appel grand jeu
- appel grand jeu grand-choeur
- appel grand jeu grand-orgue
- appel grand jeu pedale
- appel grand jeu recit
- appel grand plein-jeu
(on remplace par Anches ? Je sais pas si ça tire aussi les principaux et cornet ?)

---------------

- appel tutti fonds
- appel tutti mixtures
(pas de clavier spécifiés)
---------------

- fonds 8 grand-orgue et grand-choeur
- fonds pedale
(Pas de fonds pour un clavier particulier)

---------------

- Mixtures Péd.
- Mixtures Bomb.
---------------

- Accouplement Bomb./Pos.
- Accouplement Bomb./Réc.
- Accouplement chamade/grand-orgue
- Accouplement chamade/recit
- Accouplement chamades/grand-orgue
- Accouplement chamades/positif
- Accouplement chamades/solo
- Accouplement Ech./G.O.
- Accouplement Ech./Pos.
- Accouplement Rés./G.O.
- Accouplement Rés./Pos.
- Accouplement Ech./Rec.
- Accouplement oberwerk / hauptwerk
- copula (8) (on sais pas sur quel clavier)
- accouplement ii/i
- Accouplement G.Ch./G.O.
- Accouplement 4 G.Ch./G.O.
- Accouplement Rec./G.Ch.
- Accouplement ii/i (16/8/4)
- Accouplement ii/i (4)
- Accouplement ii/i (8)
- Accouplement ii/ii (16/8/4)
- Accouplement schwellwerk/hauptwerk
- Accouplement Solo/G.O.
- Accouplement Solo/Pos.
- Accouplement Solo/Réc.
---------------

- Tirasse I
- Tirasse II
- Tirasse (Pas pour sans clavier précisé)
- Tirasse 1er clavier 4
- Tirasse 1er clavier 8
- Tirasse Bomb.
- Tirasse Cham.
- Tirasse 4 Cham.
- Tirasse Ech.
- Tirasse hauptwerk
- Tirasse permanente Pos.
- Tirasse Rés.
- Tirasse 4 Rés.
- Tirasse Schwellwerk
- Tirasse solo
---------------

- Accouplement grand-orgue / positif
- Accouplement grand-orgue / recit
- Accouplement grand-orgue/resonnance
(Je sais pas si c'est pas plutôt l'inverse)
---------------

- octave aigue
- octave aigue par tirette sous le clavier
- octave aigue pedalier
- octave grave
- octave grave grand-choeur
- octave grave recit
- octave grave recit / grand-orgue
---------------

- combinateur informatique
- combinateur sequenciel
(Combinateur différents)
- crescendo programmable (Juste option crescendo)
---------------

- transpositeur
- transpositeur -2 / +1 demi-tons
---------------

- pedale automatique (Je sais pas ce que c'est ? une pédale d'expression ?)
---------------

- positif-coffre extractible (C'est peut être pas un accessoire ?)
---------------

- Tremblant doux G.O.
- Tremblant doux Rés.
- Tremblant fort G.O.
- Tremblant fort Rés.
- Tremblant schwellwerk
- Tremblant Solo
- Tremolo G.Ch.
---------------

- Tutti G.O.
- Tutti mixtures
- Tutti Péd.
- Tutti Pos.
- Tutti Réc.
---------------

**Comment by GwilhermPoullennec** [comment]
[accessoires.xlsx](https://github.com/inventaire-des-orgues/portail/files/6279409/accessoires.xlsx)

**Comment by GwilhermPoullennec** [comment]
Patrice, dans le tableau Excel ci-dessus tu trouveras mes commentaires et la correspondance (j'ai ajouté énormément d'accessoires);
Je te propose qu'une fois relu (pour se mettre d'accord sur les commentaires), tu en fasses un petit CSV à deux colonnes pour dépôt sous Github et correspondance dans ton script.

**Comment by patou** [comment]
Le CSV est déjà sur le github : 
https://github.com/inventaire-des-orgues/paillasse/blob/9eeb6817a06d0bce7413500b8d2df1fbf636a471/paysdelaloire/data/accessoires.csv

Merci pour avoir ajouté les accessoires

**Comment by GwilhermPoullennec** [comment]
OK, super, il sera donc à mettre à jour à partir du XSLX plus complet.

**Comment by patou** [comment]
Il me manque encore : 
- appel-retrait plein jeu positif (Donc Petit Plein Jeu ? Vu que tu as mis Grand Plein Jeu)
- appel soubasse pedale (= montre 16 grand-orgue)
- appel/renvoi forte (on peut considérer que c'est tutti ?)
- Accouplement Pos./Rés. (http://orguepaysdelaloire.fr/inventory/admin_orgue.php?id=64)
- Tutti Bombarde


Autres questions : 
Octaves Graves Récit / Grand orgue : http://orguepaysdelaloire.fr/inventory/admin_orgue.php?id=11 (c'est je pense un accouplement 16 Réc. / G.O.

Le accouplement grand orgue sur récit est sur cet orgue : http://orguepaysdelaloire.fr/inventory/admin_orgue.php?id=141
Qui possède juste un grand orgue et un positif !!! (il est en statut 3, donc validé ...)

L'accouplement grand orgue sur résonnance  c'est sur cet orgue : http://orguepaysdelaloire.fr/inventory/admin_orgue.php?id=64

Copula, c'est sur l'orgue http://orguepaysdelaloire.fr/inventory/admin_orgue.php?id=122

Les combinaisons fixes : 
http://orguepaysdelaloire.fr/inventory/admin_orgue.php?id=143
Mais on a pas le détail

**Comment by GwilhermPoullennec** [comment]
- Plein jeu Pos. (le Grand Plein jeu étant plein jeu + anches ou cornet je ne sais jamais, donc différent de Plein jeu G.O.)
- Soubasse Péd. (ajouté, assez courant)
- Forte (ajouté, car appelation romentique de Tutti ? Et il y a nuance je pense (Forte = sans mixture, Tutti = tout))
- Accouplement Pos./Rés. (ajouté)
- Tutti Bombarde (ajouté)

- Octaves Graves Récit / Grand orgue -> oui Accouplement 16 Réc./G.O.
- Accouplement G.O./Réc. -> c'est quasiment à coup sûr une erreur, à corriger -> Accouplement Pos./G.O., ou même plus probablement Accouplement Réc./G.O. avec une erreur sur le nom du clavier (d'ailleurs les autres accessoires ne correspondent pas !)
- Accouplement G.O./Rés. -> cela semble possible, la Résonnance semblant être sous le grand orgue (présence du B16).
- Copula -> il doit y en avoir beaucoup en France, courant à l'époque romantique (le 8 est facultatif, c'est 8 par défaut)
- Combinaisons -> OK, on laisse Combinaison, on met 5 fois Combinaison, ou bien on peut mettre Combinateur (c'est un Beuchet avec probablement des boutons de combinaison sous les claviers, plus ou moins programmables par derrière. "Séquenceur" permet de distinguer ce type d'installation d'un vrai séquenceur avec flèche pour avancer et reculer dans les combinaisons (qui est le standard à l'heure actuelle).

Merci infiniement, tout cela est super et aura permis d'enrichir intelligemment la liste des accessoires !

**Comment by patou** [comment]
Merci, ma liste est complète
