### ISSUE TITLE
Ajout de facteurs

### ISSUE THREAD

**Issue by patou** [inventaire-des-orgues/portail#422]
# Facteurs

Ajout de facteur qui sont dans l'inventaire des pays de la loire.

- Alizon (Mirecourt début XIXe siècle)
- Baldner, Jean-Frédéric (Existe Baldner, et Baldner Johan Jacob)
- Baudot, Evrard
- Bedel & Isambart
- Beurtin Paul
- Holdich George Maydwell
- Guillouard Armand
- Hulbert
- Lapeyre
- Lusson Florentin
- Manufacture Berrichon Grande Orgue (MBGO, Hédelin Marc)
- Perroux Jean
- Le Hellocq Pierre (Dans la base on a Le Helloco Pierre ou Le Hellocq)
- Schreder
- Tolbecque Auguste

**Comment by GwilhermPoullennec** [comment]
Fait.
Première orthographe pour Le Hellocq.
Idem Baldner.

**Comment by patou** [comment]
Pour "Manufacture Berrichon Grande Orgue (MBGO, Hédelin Marc)"
En faite le nom de l'entreprise c'était (car je viens de remarqué que Marc Hédelin est mort en novembre dernier, j'avais fais mon stage de 3 ième avec lui) : "Manufacture de grandes orgues HEDELIN et cie" (Dans la base il existait déjà en tant que Hédelin Marc), et souvent on trouve l'abréviation MBGO.

**Comment by GwilhermPoullennec** [comment]
OK, j'ai ajouté ce libellé.
Il semble que les deux aient existé, car le nom berrichon (enregistré à Alençon...) existe au greffe. Il y a couramment plusieurs noms d'entreprise pour un facteur, ce qui fait que j'étais parti sur l'idée de ne mettre que les noms propres (ce qui permet par ailleurs de valoriser les collaborateurs principaux, souvent oubliés), mais c'est un vaste débat.

JM Cicchero nous aidera certainement (cf. son bouquin recensant tous les facteurs d'orgues). A suivre donc.
