### ISSUE TITLE
Ajout de type de clavier

### ISSUE THREAD

**Issue by patou** [inventaire-des-orgues/portail#423]
Voici des types de claviers à ajouter.
Utilisé dans l'Inventaire des pays de la Loire.

- Chamade
- Schwellwerk
- Accouplement (Clavier accouplement permanent)

**Comment by patou** [comment]
Wikipedia liste un certains de nombres de nom de clavier : https://fr.wikipedia.org/wiki/Clavier_(orgue)

**Comment by GwilhermPoullennec** [comment]
Fait.
Pour Accouplement, de quel orgue s'agit-il ?

**Comment by GwilhermPoullennec** [comment]
Vu ! J'ai créé "Clavier d'accouplement" dans les accessoires
