### ISSUE TITLE
Afficher le nombres d'orgues complété par %

### ISSUE THREAD

**Issue by patou** [inventaire-des-orgues/portail#424]
Sur la page d'accueil : 
Dans les statistiques pour les régions/département, il pourrait être intéressant d'afficher le nombres d'orgues complété à 100% et par tranche de 30%.
Cela permet de savoir dans quel département essayer de compléter les orgues.

Je crois que c'est disponible dans le dashbord, mais ça pourrait être une donnée afficher de manière publique.

**Comment by Amaryllis25** [comment]
Oui je vois. A la limite faire un onglet Etat pour les statistiques, et un onglet dynamique "Avancement". Je vais me renseigner sur comment récupérer les taux d'avancements des orgues.

**Comment by GwilhermPoullennec** [comment]
#435

**Comment by GwilhermPoullennec** [comment]
Dans un premier temps, juste afficher le taux d'avancement moyen par département, ce sera simple mais effectivement utile !

**Comment by Amaryllis25** [comment]
D'accord je vois ! Je vais chercher comment faire ça !

**Comment by Amaryllis25** [comment]
Du coup les taux moyens d'avancements, en m'inspirant du dashboard semble donctionner. Ils marchent au niveau départemental et régional. Il semble qu'il y ai encore un petit bug pour le niveau national. J'ai corrigé un bug concernant Mayotte dans les régions par hasard. 

J'ai aussi rajouté les bulles statistiques, il me semble que j'avais oublié de rajouter celui pour les orgues classés ou inscrits aux monuments historiques donc je l'ai également rajouté.

**Comment by Amaryllis25** [comment]
Une erreur statistique à corriger dans le cadre de Mayotte. Puisqu'il y a 0 orgue actuellement à Mayotte il ne devrait pas intervenir dans le calcul national moyen. Je m'occupe de cela d'ici la fin de semaine.

**Comment by GwilhermPoullennec** [comment]
Cf. #494 : en quittant la carte de France, le curseur doit réinitialiser les statistiques pour toute la France.
Pour le reste, je ne sais pas si les corrections d'Amaryllis ont été prises en compte.

**Comment by Amaryllis25** [comment]
Je n'avais pas fini d'apporter cette correction il me semble

**Comment by patou** [comment]
Je vais refaire la gestion de la carte, car ça commence à être très complexe à comprendre et modifier.
Et il y a plusieurs appel au back qui sont fait.
Je vais changer pour ne faire qu'une requette pour avoir toutes les données en une fois.
Je pensais aussi modifier pour utiliser vuejs plutôt que jquery comme sur la page de recherche.
