### ISSUE TITLE
Statistiques carte accueil

### ISSUE THREAD

**Issue by Amaryllis25** [inventaire-des-orgues/portail#426]
Bonjour M. Berbesson ! 

J'aurai quelques questions concernant les requêtes AJAX (qui me donne encore un peu de fil à retordre !). Je fais donc des tests pour la carte d'accueil : je dois rajouter des statistiques sur celle-ci concernant les orgues. 
![image](https://user-images.githubusercontent.com/79219571/113838093-bf907e00-978e-11eb-9993-2b3d90b8f73c.png)

Du coup, j'ai bien compris en fouillant le json qu'un orgue classé ou inscrit aux monuments historiques se trouve dans la catégorie "evenements" (jusque-là pas de problème). Cependant, evenements contient de multiples informations (un nouveau dictionnaire), à l'inverse de "etat". Du coup j'ai essayé de réindexer "valeurs", pour accéder seulement au "type", une des clés du dictionnaire que contient evenements, et qui permet de trouver si oui oui non un monument est classé ou inscrit, mais cela ne semble pas probant.

Pourriez-vous m'aiguillez ?

**Comment by GwilhermPoullennec** [comment]
Attention, petite subtilité, l'information orgue inscrit ou orgue classé dans la catégorie évènement n'est qu'un recopie (arbitraire) de l'information originelle qui est l'attribut references_palissy.
C'est donc ce dernier attribut qu'il faut utiliser pour réaliser des statistiques.
Il s'agit d'une liste de numéros débutant par "PM".
De la sorte il n'est pas possible de distinguer inscription ou classement, mais ce n'est pas grave.

Il faut donc regarder simplement pour des statistiques si la liste references_palissy est non vide. Si elle non vide, l'orgue en question est inscrit ou classé.

**Comment by Amaryllis25** [comment]
Ah d'accord, je vais regarder ça, merci !

**Comment by Amaryllis25** [comment]
Ca marche c'est bon !
