### ISSUE TITLE
Bas de page : menus non centrés

### ISSUE THREAD

**Issue by Amaryllis25** [inventaire-des-orgues/portail#427]
![image](https://user-images.githubusercontent.com/79219571/113839645-2a8e8480-9790-11eb-85b8-9d53de9d7b52.png)
Il semble qu'un rajout récent ait modifié le centrage en pied de page, voulez-vous que je regarde ça ?

**Comment by GwilhermPoullennec** [comment]
A l'occasion, mais pas urgent.
Il faudrait effectivement que l'on utilise les même classes bootstrap pour que les colonnes soient bien alignées entre logos et menus de pied de page.

**Comment by LucasBerbesson** [comment]
cf #107
