### ISSUE TITLE
Taux avancement

### ISSUE THREAD

**Issue by Amaryllis25** [inventaire-des-orgues/portail#435]
Bonsoir M. Poullennec et M. Berbesson,

Je suis en train de regarder un peu la base de données et les différentes pages html du projet. J'aimerais savoir comment est calculé le taux d'avancement de la fiche d'un orgue ?

En effet, je vois diverses variables comme "orgue.completion", mais je n'arrive pas à voir où celle-ci a été calculée, ne la trouvant pas directement dans le fichier json (comme pour dans le html de orgue-detail-avancement). Pourriez-vous m'éclairer ?

Bonne soirée !

**Comment by GwilhermPoullennec** [comment]
models.py
    def calcul_completion(self):

**Comment by LucasBerbesson** [comment]
Bonsoir, 
La fonction qui calcule le taux d'avancement est ici : 

https://github.com/inventaire-des-orgues/portail/blob/52344722c267729ef7a737ca7a77d9c50a362bd7/orgues/models.py#L472

Elle est lancée à chaque fois qu'on enregistre un orgue ou un clavier : 

https://github.com/inventaire-des-orgues/portail/blob/52344722c267729ef7a737ca7a77d9c50a362bd7/orgues/models.py#L301

https://github.com/inventaire-des-orgues/portail/blob/52344722c267729ef7a737ca7a77d9c50a362bd7/orgues/models.py#L539
