### ISSUE TITLE
Ajouter un commentaire sur le clavier

### ISSUE THREAD

**Issue by patou** [inventaire-des-orgues/portail#437]
Il pourrait être intéressant d'ajouter un commentaire sur les claviers pour permettre d'ajouter des informations intéressantes :

- Positif coffre extractible
- Octave courte (6 ou 7 notes sur la première octave)
- Tirasse permanente
- Clavier transpositeur
- Machine barker sur un seul clavier
- Transmission différente sur le clavier
- plan sonore décalé
- clavier d'emprunt (pas de jeux propre, que des jeux d'emprunt des autres claviers)
- Pédalier à la française
- ...

**Comment by GwilhermPoullennec** [comment]
Oui, nous avions songé à cette solution simple qui permet d'éviter de rajouter moult champs typés et laisse la place à la description de particularités (notamment celles assez courantes que tu énumères, il y a souvent le cas des pédaliers électriques sur orgue mécanique par exemple).

**Comment by patou** [comment]
Je peux le développer si vous voulez...
