### ISSUE TITLE
QRcode par fiche

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/portail#449]
dans le cartouche au-dessus du bouton Compléter

**Comment by patou** [comment]
> Le télécharger en cliquant dessus (par exemple PDF assez gros centré sur page blanche).

Si c'est pour inciter à l'afficher dans l'église, le pdf devrait contenir un texte présentant le projet d'inventaire de l'orgue.

**Comment by GwilhermPoullennec** [comment]
Bonne idée !

**Comment by GwilhermPoullennec** [comment]
#479
