### ISSUE TITLE
[Ajout d'un plan sonore] Type devient Nom

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/portail#45]

**Comment by GwilhermPoullennec** [comment]
Pas sûr donc que l'on est besoin de l'objet TypeClavier, si ?

**Comment by LucasBerbesson** [comment]
On laisse les gens entrer ce qu'ils veulent ?

**Comment by GwilhermPoullennec** [comment]
Non, à l'usage ce doit rester une liste déroulante.
