### ISSUE TITLE
Demander vérification avant de supprimer un fichier

### ISSUE THREAD

**Issue by CelestinHuet** [inventaire-des-orgues/portail#450]
Pour un fichier, lorsque l'on clique sur supprimer, le fichier est immédiatement supprimé. Il faudrait ajouter un message demandant si l'on est certain de vouloir supprimer le fichier.

**Comment by GwilhermPoullennec** [comment]
En précisant de ne pas supprimer les fichiers des livres d'inventaire...

**Comment by LucasBerbesson** [comment]
Oui bonne idée, il faut s'inspirer du mécanisme mis en place pour les images en passant par une template `fichier_confirm_delete.html`

**Comment by GwilhermPoullennec** [comment]
Célestin, j'ai testé sur l'orgue de Troyes, Saint-Nicolas, en tribune.
J'ai une erreur 500
https://inventaire-des-orgues.fr/fichiers/suppression/22940/?csrfmiddlewaretoken=gb01oU6i6B7o9qfOh5PfFqRVOJOoIYqb97AJWECKBczLUM1FRhWJbtPaeemgfUFV

**Comment by GwilhermPoullennec** [comment]
(erreur interne serveur)
