### ISSUE TITLE
Ergonomie ajout d'image

### ISSUE THREAD

**Issue by patou** [inventaire-des-orgues/portail#451]
Il y a plusieurs soucis sur l'ergonomie de l'ajout d'image : 
- Lorsque l'on upload des images sur le site, le bouton retour n'est pas claire, même si c'est enregistrer automatiquement, un bouton enregistrer serait moins déroutant.
- Si on clique sur retour alors que l'image n'est pas finit d'être sauvegardé, alors l'image n'est pas enregistré.
- Avoir une prévisualisation des images lors de l'envoie de l'image
![image](https://user-images.githubusercontent.com/841858/114789544-9326c400-9d83-11eb-8fd9-1f4148d2dd0a.png)
(plugin filepound https://pqina.nl/filepond/docs/patterns/plugins/image-preview/)
- Lorsque l'on modifie une vignette, on change la vignette, on clique sur enregister et on revient sur la page avec la nouvelle vignette, mais le cadre sur notre photo revient comme avant, c'est vraiment déroutant, on pense que la vignette n'est pas enregistrer. Et on a pas de bouton retour, seulement un nouveau bouton enregistrer qui va remplacer la vignette par le cadrage par défaut. On ne sait plus quoi faire.
- Lorsque l'on ajoute une image, on pourrait avoir le champ Crédit pré remplis par notre prénom et nom.

**Comment by GwilhermPoullennec** [comment]
Oui, j'ai parfois été dérouté !

Concernant le dernier item (crédit pré-rempli), le cas échéant il faudrait peut-être soigner le libellé ou vérifier le help_text, car il ne faut pas que les utilisteurs deviennent paresseux sur la mention du crédit, et laissent leur nom plutôt qu'un autre.

**Comment by patou** [comment]
> Oui, j'ai parfois été dérouté !
> 
> Concernant le dernier item (crédit pré-rempli), le cas échéant il faudrait peut-être soigner le libellé ou vérifier le help_text, car il ne faut pas que les utilisteurs deviennent paresseux sur la mention du crédit, et laissent leur nom plutôt qu'un autre.

J'ai fait une nouvelle MR pour améliorer l'ajout d'image, on a un lien en dessous du champ crédit qui permet de remplir automatiquement le champ avec notre nom.
![image](https://user-images.githubusercontent.com/841858/115260612-36385e80-a133-11eb-9120-9fdb73f80d2e.png)
