### ISSUE TITLE
Problème select2 de jquery sur le filtre de la carte

### ISSUE THREAD

**Issue by CelestinHuet** [inventaire-des-orgues/portail#453]
Sur certains ordinateurs mais pas tous (pas sur le mien notamment), le menu déroulant des filtres par facteurs à droite de la carte ne fonctionne pas. Voici une capture d'écran du problème.
![image](https://user-images.githubusercontent.com/79277114/114979215-c0aa6500-9e8a-11eb-8e97-54ed6c9d7aa6.png)

**Comment by GwilhermPoullennec** [comment]
La carte marche désormais de mon côté, ce qui n'était pas le cas avant, je ne sais si quelque chose à changé...

**Comment by CelestinHuet** [comment]
Je crois que ce problème a été résolu dans #539
