### ISSUE TITLE
Avancement d'un orgue

### ISSUE THREAD

**Issue by Amaryllis25** [inventaire-des-orgues/portail#454]
Bonsoir M. Berbesson,

Je réfléchis depuis un moment à comment renvoyer le taux de complétion en dehors du python lorsqu'on instancie l'orgue. En effet, il semble que que calcul_completion() se serve d'info_completion() (bon ça je vais le chercher).

Cependant, elle se lance lorsqu'on enregistre un orgue. Je me demandais s'il n'y avait pas un moyen d'enregistrer à partir d'ici un json ou un txt, contenant un département et tous ses taux d'avancements ? Puis de le traiter séparément, celui-ci pourrait être ainsi mis à jour à chaque nouvelle rentrée d'orgue ?? Ou peut-être y a-t-il plus simple, car je ne vois pas trop comment je peux récupérer ce taux avec de javascript.

Bonne soirée,

Amaryllis Vignaud

**Comment by GwilhermPoullennec** [comment]
S'inspirer de OrgueListJS() de views.py en ajoutant 'completion' dans values

Et dans Javascript s'inspirer de carte.html
$.getJSON("{% url 'orgues:orgue-list-js' %}"

**Comment by LucasBerbesson** [comment]
L'avancement par département est déjà calculé à la volée sur la page [http://localhost:8000/dashboard/](http://localhost:8000/dashboard/)
Vous pouvez vous inspirer du code présent.  
Attention, le taux d'avancement par département bouge très souvent, pas seulement à la création de nouveaux orgues. Je déconseille de figer les résultats dans un fichier txt.
