### ISSUE TITLE
Filtre carte : Loupe qui virevolte quand la souris survole le bouton

### ISSUE THREAD

**Issue by CelestinHuet** [inventaire-des-orgues/portail#456]
Dans le filtre de la carte, il y a une animation inutile quand la souris survole les boutons permettant de valider. J'ai mis les mêmes paramètres de classes css que pour le bouton de la page d'accueil, mais le rendu n'est pas le même et je ne comprends pas pourquoi.

**Comment by LucasBerbesson** [comment]
Remplacer `btn-slide` par `btn-rounded`
