### ISSUE TITLE
Ouvrir une page CreateView

### ISSUE THREAD

**Issue by CelestinHuet** [inventaire-des-orgues/portail#460]
J'ai ajouté un bouton pour ouvrir une page où l'on peut créer un nouvel orgue. Mais lorsque je clique sur ce bouton, j'ai le message suivant et je ne parviens pas à résoudre le problème.
Le problème est sur la branche nouvelle_fiche et le bouton se trouve à gauche de la liste des orgues lorsque l'on clique sur l'onglet "Les orgues".
![image](https://user-images.githubusercontent.com/79277114/115406100-25e5b980-a1ef-11eb-9f01-94c1a1c1281e.png)

**Comment by patou** [comment]
J'ai regardé un peu, je ne trouve pas non plus.
Je me demande si c'est pas ce code dans le modèle Orgue: 
```
    def get_absolute_url(self):
        return reverse('orgues:orgue-detail', args=(self.slug,))
```

**Comment by LucasBerbesson** [comment]
Bonjour, 
La vue que vous essayez de créer `OrgueCreate` n'a pas de variable `template_name` ce qui veut dire qu'elle utilise la template html par défaut `orgue_form.html` (cf doc django).    
Cette template hérite de :
```
{% extends 'orgues/base_edition.html' %}
```
Si vous regardez `base_edition.html` vous verrez qu'il y a des liens utilisants l'instance `orgue` absolument partout : 
<img width="753" alt="Capture d’écran 2021-04-20 à 21 08 57" src="https://user-images.githubusercontent.com/8393585/115450915-c9998e80-a21c-11eb-9f08-0c3910de03bc.png">

Dans une vue de création, cette instance d'orgue est par définition absente, donc tous les liens bugs.  
C'est ce qu'explique la page jaune que vous voyez : 

> reverse for 'orgue-detail' with argument '' not found.

Autrement dit: impossible de générer l'url 'orgue-detail' pour un orgue inexistant.  
Normalement l'argument en question est différent de '' car l'orgue est présent.   

Vu qu'il y a beaucoup de liens et qu'il ne faut pas casser la structure d'édition existante, je pense que la meilleure solution est de faire une template spécifique de création `orgue_create.html` qui n'hérite pas de `base_edition.html` (mais plutôt de `base.html`) et qui propose un formulaire simplifié de création avec les 3 champs les plus importants. Ensuite quand l'utilisateur enregistre on le redirige vers la vue de modification standard où il pourra retrouver tous les formulaires existants.
