### ISSUE TITLE
Erreur 500 sur une fiche

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/portail#463]
https://inventaire-des-orgues.fr/detail/orgue-saint-etienne-eglise-notre-dame-fr-42218-sseti-ndamev1-x/

**Comment by GwilhermPoullennec** [comment]
A 20h56 le 23 avril par exemple.
Erreur 500 parfois, parfois pas.

**Comment by LucasBerbesson** [comment]
C'est corrigé, il s'agissait d'une image manquante sur le disque mais présente en base de données
