### ISSUE TITLE
Attribution d'une permission renforcée sur les évènements MH

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/portail#464]

**Comment by GwilhermPoullennec** [comment]
Est-ce faisable sans compliquer encore ?
En créant des évènement spécifiques (classe dupliquée) ? ou en mettant un if quelque part ?

**Comment by GwilhermPoullennec** [comment]
Même question pour les fichiers (protéger les liens vers les livres d'inventaires).

**Comment by LucasBerbesson** [comment]
Il y a plusieurs options pour faire ça, plus ou moins sécurisées. 
Pour les évènements MH le plus simple est : 
```html
{% if perms.orgues.add_orgue and not evenement.is_locked %}
        <a href="{% url 'orgues:evenement-update' evenement.pk %}" class="btn btn-xs btn btn-outline">modifier</a>
        <a href="{% url 'orgues:evenement-delete' evenement.pk %}" class="btn btn-xs  btn-danger btn-outline supprimer_evenement" data-pk="{{ evenement.pk }}">Supprimer</a>
{% endif %}
```

```python
class Evenement(models.Model):
    ...
    @property
    def is_locked(self):
        return self.type not in ["classement_mh", "inscription_mh"]

```
Ce qui n'empêche cependant pas de deviner le lien (pour ça il faut surcharger la méthode `dispatch` de `EvenementUpdate` mais je ne pense pas que ce soit utile)

Pour les fichiers c'est un peu plus compliqué car on a pas de type.  
Soit on en ajoute un, soit on ajoute un champ booléen `is_locked` modifiable depuis admin ou script, soit on enregistre les utilisateurs qui ont chargé les fichiers et on fait en sorte qu'ils ne puissent modifier que les leurs.
