### ISSUE TITLE
Contrôle sur l'id_osm

### ISSUE THREAD

**Issue by Johan-Leclercq** [inventaire-des-orgues/portail#480]
J'ai repéré que dans la partie localisation de certaines fiches d'orgues, le champ "id open street map" n'est pas renseigné avec avec l'id de l'objet OSM correspondant à l'édifice de l'orgue, mais au nom d'utilisateur osm de celui qui a rempli la fiche.

Par exemple, pour l'orgue  de Viroflay : 
![image](https://user-images.githubusercontent.com/79969120/116789162-cd939f00-aaad-11eb-9a56-95c0cb57f3e2.png)

L'objet a été localisé et les latitude/longitude sont bien renseignées (et correspondent bien sur la carte), mais nous n'avons pas de moyen de connecter l'orgue à l'objet OSM, ce qui peut poser problème pour certains scripts.

Faut-il prévoir un moyen de détecter et corriger ces erreurs de remplissage ou bien faut-il juste prévoir une exemption dans les scripts utilisant l'id_osm pour éviter les bugs ?
Faut-il corriger la documentation pour éviter que cela se reproduise ou faire un test de conformité dans le champ ?

**Comment by GwilhermPoullennec** [comment]
Merci Johan.
L'idéal est d'ajouter un expression régulière sur ce champ id_osm.

**Comment by GwilhermPoullennec** [comment]
Par ailleurs, je mets à jour les libellés.
