### ISSUE TITLE
Quand une région est sélectionnée le bouton Voir les orgues doit renvoyer la recherche avec les orgues de cette région

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/portail#491]

**Comment by GwilhermPoullennec** [comment]
A défaut, le cacher et ne l’afficher que pour les départements et la France.

**Comment by patou** [comment]
Quand je l'avais mis en place, j'avais pas trouvé de moyen de faire une recherche par Région, mais effectivement, il faudrait ajouter la region comme une nouvelle facette de recherche pour pouvoir ajouter le filtrage par région.
