### ISSUE TITLE
Sélection impossible des facteurs d’orgues

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/portail#492]
Dans un événement, impossible de sélectionner un facteur de la liste déroulante.

**Comment by LucasBerbesson** [comment]
@CelestinHuet La vue `FacteurListJS` est utilisée dans la sélection des facteurs dans les formulaires, "id" doit être égal à u.id, sinon ça ne marche plus

https://github.com/inventaire-des-orgues/portail/blob/e37df92a1a73d126803ca0688f4bd0c104ae5261/orgues/views.py#L639

**Comment by CelestinHuet** [comment]
En modifiant seulement cette ligne de code, le filtre sur la carte ne fonctionne plus sur la branche master. Le commit ci-dessus 243c50f règle correctement les deux problèmes et n'est que sur la branche dev pour le moment.

**Comment by LucasBerbesson** [comment]
Ok j'ai pioché les modifications dans 243c50f pour les intégrer directement sur master
