### ISSUE TITLE
Carte accueil

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/portail#494]
Quand on ne survole plus la carte de France, les décomptes à droite de la carte doivent concerner toute la France (or actuellement la dernière région survolée reste rémanante).

**Comment by Amaryllis25** [comment]
Il y a également un autre bug : depuis le rajout de la carte en fond par patrick, le bouton de retour à la vue régional de marche plus.

**Comment by Amaryllis25** [comment]
Je n'ai rien dit, cela marche sur le site mais pas chez moi étonnement ! Je vais regarder pourquoi, je vais chercher une solution concernant l'autre bug.

**Comment by patou** [comment]
Je vais refaire le code de gestion des statistiques sur la carte d'accueil comme dit dans l'issue https://github.com/inventaire-des-orgues/portail/issues/424#issuecomment-895099017

**Comment by GwilhermPoullennec** [comment]
OK, je ferme pour rester uniquement sur le fil du ticket #424
