### ISSUE TITLE
Modification des utilisateurs impossible

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/portail#508]
Dans l'admin, je ne parviens pas à corriger les nom et prénom des utilisateurs : l'enregistrement ne modifie pas les champs.

**Comment by patou** [comment]
@LucasBerbesson C'était lié à ce que j'avais développé ? C'est vrai que j'avais pas testé depuis l'admin ?

**Comment by LucasBerbesson** [comment]
Je sais pas... est-ce que ça remarche ?

**Comment by GwilhermPoullennec** [comment]
Visiblement oui !
