### ISSUE TITLE
Tempérament

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/portail#51]

**Comment by GwilhermPoullennec** [comment]
Texte libre.
Petite note d'information dessous : "Mention la plus précise possible. Ex: mésotonique au sixième modifié.".

**Comment by GwilhermPoullennec** [comment]
longueur max = 50 car.

**Comment by LucasBerbesson** [comment]
à ajouter dans "Partie Instrumentale"
