### ISSUE TITLE
Mettre une icône QrCode un peu plus lisible et plus grosse

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/portail#512]
https://thenounproject.com/search/?q=qr%20code

**Comment by patou** [comment]
On pourrait pas demander au graphiste de nous faire une image dans le style de ceux sur la premières page ?

**Comment by patou** [comment]
Top, l'image, on comprend vraiment bien le principe.
En espérant voir apparaitre plein de panneau de ce style dans les églises.
