### ISSUE TITLE
Recherche sur la carte et géolocalisation

### ISSUE THREAD

**Issue by patou** [inventaire-des-orgues/portail#515]
Il serait bien de pouvoir chercher sur la carte une adresse et centrer la carte sur cette adresse. Et pouvoir utiliser la géolocalisation  pour centrer la carte.

L'idée est :
Je suis en vacances, je veux chercher les orgues qui sont autour de moi pour aller les visiter.

**Comment by GwilhermPoullennec** [comment]
Oui, a minima la partie "autolocalisation" pour les terminaux portables et bien commode en déplacement.
