### ISSUE TITLE
Jeu avec Basse ET Dessus

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/portail#525]
Pouvoir cocher les deux cases.
A voir pour le décompte des jeux.

**Comment by patou** [comment]
On peut pas mettre deux lignes ?

Trompette 8 Basse
Trompette 8 Dessus 

??

**Comment by GwilhermPoullennec** [comment]
Si tout à fait, mais les contributeurs ont fortement tendance, le cas échéant, à ne mettre qu'un seul jeu avec en commentaire "basse et dessus".
Probablement pour ne pas modifier le décompte des jeux et alourdir la liste.

**Comment by patou** [comment]
Je comprend, pourquoi ne pas remplacer la liste déroulante Basse et Dessus, par un champ d'autocomplexion (comme les accessoires) et ainsi de permettre de saisir basse et dessus, mais aussi d'autres caractéristiques comme : 
- Emprunt
- Extensions
- ...

**Comment by GwilhermPoullennec** [comment]
OK, pour l'instant on démarre en ajoutant "Basse et Dessus"
