### ISSUE TITLE
Carte : Filtres

### ISSUE THREAD

**Issue by patou** [inventaire-des-orgues/portail#528]
Les filtres sur la cartes ne sont pas très pratiques, il faut sélectionner un facteur, puis cliquer sur rechercher pour lancer une recherche. Une mise à jour en direct en fonction des filtres serait pratique.
De plus c'est limité à seulement le facteur d'orgue.
Il serais intéressant d'avoir un filtrage plus précis : 
- par mot clé (comme la recherche)
- par facteur
- par nombre de claviers (plus de 3 claviers)
- par nombre de jeux (plus de 30 jeux, moins de 10 jeux)
- par classement monument historique
- par état de fonctionnement
- par emplacement
- ...

**Comment by CelestinHuet** [comment]
J'ai amélioré le filtre. Par contre, on ne peut plus afficher directement depuis la carte dans l'onglet "les orgues" la liste des orgues du facteur sélectionné dans le filtre

**Comment by patou** [comment]
@CelestinHuet je vais tester ton code, peut tu créer une PR pour pouvoir faire les commentaires.
Cela me semble une bonne etape.

Je vois beaucoup de code JavaScript duplique, ton système nombre de change pour les sliders qui peut être améliorer en faisant un cancel du setTimeout.
Faire un cancel de la requête Ajax précédente.
Le compte des claviers prend en compte le pédalier.
Côté back, n'ajouter les filtres que si le filtre est actif.
...

Gérer la version mobile des filtres (pour l'instant j'ai simplement cacher les filtres).

**Comment by patou** [comment]
J'avais penser faire tous les filtres côté front pour une meilleur reactivité.

**Comment by CelestinHuet** [comment]
Effectivement, je vois qu'il y a peut-être plus simple pour annuler une requête Ajax. Je vais l'améliorer.
Pour le nombre de claviers, je crains que mettre le pédalier à part alourdisse le filtre (il faudrait dans ce cas ajouter une autre case dans le filtre pour sélectionner les instruments avec ou sans pédaliers), mais en même temps, je reconnais que ça prête à confusion. 
Qu'entends-tu par mettre les filtres côté front ?

**Comment by patou** [comment]
> Effectivement, je vois qu'il y a peut-être plus simple pour annuler une requête Ajax. Je vais l'améliorer.
Sans jquery tu as debounce pour lancer la recherche 300ms apres.
https://stackoverflow.com/questions/27787768/debounce-function-in-jquery



> Pour le nombre de claviers, je crains que mettre le pédalier à part alourdisse le filtre (il faudrait dans ce cas ajouter une autre case dans le filtre pour sélectionner les instruments avec ou sans pédaliers), mais en même temps, je reconnais que ça prête à confusion. 

Au lieu de faire une liaison sur les claviers tu peut utiliser le champ calculé resume_composition

Et plutôt des checkbox pour sélectionner les claviers plutôt qu'un double sliders :

Claviers  ⬜ I ✅ II ✅ III ⬜ IV ⬜ V ✅ P

Et donc ton filtre sera resume_composition IN ("II/P", "III/P")

> Qu'entends-tu par mettre les filtres côté front ?

Je voulais dire : télécharger le json avec toutes infos (nom, ville, facteurs, état, ...)
Puis ne plus faire de requête, tu parcours simplement le tableau JS pour construire le tableau filtré à afficher.
