### ISSUE TITLE
Barker : descendre au niveau clavier

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/portail#54]
La présence au non d'une "machine Barker" doit être au niveau d'un clavier/pédale.
Nota : la machine Barker est un ensemble de relais pneumatiques, un pour chaque note, permettant la traction des soupapes avec force dans de très grands instruments avec claviers accouplés.

**Comment by GwilhermPoullennec** [comment]
Je mets à plus tard, car en réalité c'est toute la transmission des notes qu'il faudrait descendre au niveau du plan sonore (clavier) : il est fréquent que la pédale soit électrifiée, par les claviers, par exemple. Mais c'est sans fin.
Idem pour la traction des jeux que l'on pourrait s'amuser à descendre au niveau du jeu.
Donc stop.

**Comment by patou** [comment]
Après si c'est un champs texte, si il y a des différences il suffit de l'indiquer dans le champs simplement sans complexifier le modèle ni la saisie.

**Comment by GwilhermPoullennec** [comment]
Je suis d'accord et propose qu'on en reste là pour l'instant.
