### ISSUE TITLE
Les orgues n'apparaissent plus sur la carte

### ISSUE THREAD

**Issue by CelestinHuet** [inventaire-des-orgues/portail#542]
Dans la console, il y a le message suivant : Failed to load resource: the server responded with a status of 502 (Bad Gateway)

**Comment by patou** [comment]
Oui, j'ai demandé quel est le message sur le serveur.
Avec mes données en local, je n'ai pas de soucis

**Comment by GwilhermPoullennec** [comment]
A partir de quel commit exactement cela a-t-il planté ?

**Comment by patou** [comment]
Je sais pas, c'est quand tu as mergé toutes les PR.
Mais est-ce qu'on a moyen de voir les logs de l'application python ?

**Comment by GwilhermPoullennec** [comment]
Les logs Django sont redirigés chez FabDev, qui devait faire un fork pour que l'on puisse débugger.
Je jetterai tout à l'heure un oeil sur le serveur voir ce que je peux récupérer.

**Comment by patou** [comment]
Oui ça serait bien si on pouvait avoir une autre instance pour tester avant
de mettre en ligne des choses qui marchent plus !!!

Patrice de Saint Steban

**Comment by LucasBerbesson** [comment]
Le problème vient de `orgues.views.OrgueListJS` qui met beaucoup trop de temps à s'éxecuter (2/3 minutes ... requête SQL trop lourde). On ne peut pas utiliser un `serializers.ModelSerializer` ici. Il faut soit passer par un `queryset.values`, soit générer le fichier json une fois pour toute et le cacher.

**Comment by LucasBerbesson** [comment]
Je vais reprendre cette partie

**Comment by patou** [comment]
En attendant, j'ai supprimé la vignette, le JSON s'affiche maintenant, juste un peu long au démarrage, mais après le filtrage est très rapide.

**Comment by LucasBerbesson** [comment]
Chez moi les marqueurs mettent pas loin de 30 secondes à se charger...
Il faut utiliser : 
```python
JsonResponse(list(Orgue.objects.values("slug","latitude","longitude","commune","edifice","resume_composition")),safe=False)
```
(moins de 1 seconde de chargement pour les 8000+ orgues)
Et faire du filtrage en Django plutôt qu'en Javascript.

On peut aussi mettre en place une fenêtre de popup dynamique qui ne charge les informations additionnelles qu'une fois que l'utilisateur a cliqué sur le marqueur.

**Comment by patou** [comment]
J'ai l'impression que maintenant le seul truc qui est encore lent, c'est la récupération de la liste des ids de facteurs.

Le filtrage en JS une fois le json téléchargé est très performant et fonctionne plutôt bien.

Pour l'affichage de la popup, je viens de faire le chargement dynamique des donnés : 
https://github.com/inventaire-des-orgues/portail/commit/2d0158538fe227ecee9780e6a48ff95c732f7f37
(j'ai par erreur pousser sur master sans faire de MR).

**Comment by LucasBerbesson** [comment]
Oui effectivement aujourd'hui on fait une requête additionnelle pour chaque orgue pour aller chercher les facteurs, c'est ce qui prend du temps.

**Comment by LucasBerbesson** [comment]
En fait d'une façon générale je pense qu'il faut fusionner les 2 moteurs de recherche des pages "carte" et "orgues", quitte à améliorer celui de la page "orgues" qui pour l'instant ne permet pas de chercher par nbr de jeux, etc...
Cela permettra de réduire le nombre de lignes de code du projet tout en simplifiant l'interface et la navigation.
La carte ne devrait être qu'un "mode d'affichage".  
Aujourd'hui les facteurs, les vignettes et les données des orgues sont figées dans un index de recherche "meilisearch" pour permettre les recherches et les accès rapides. Il faut essayer de repasser le plus possible par la, et changer meilisearch par un autre moteur de recherche (elasticsearch par exemple) si ça nous bloque.

**Comment by patou** [comment]
J'y avais pensé d'utiliser meilisearch, mais le problème c'est que meilisearch ne retourne qu'un nombre limité de résultats or la carte affiche tous les orgues, ce qui veut dire récupérer tous l'index de meilisearch.

**Comment by LucasBerbesson** [comment]
Une solution serait d'utiliser le niveau de zoom de mapbox.   
Quand la carte est très dézoomée on affiche juste le dataset des 93 départements avec le total par département. 
Quand on clique sur un département ou quand on zoom suffisamment, on lance une requête avec latitude_min, latitude_max, longitude_min, longitude_max pour récupérer les orgues de la zone via meilisearch. 
Il faudra juste ajouter les attributs "latitude" et "longitude" à meilisearch.

**Comment by LucasBerbesson** [comment]
Et en mode carte on retire la pagination meilisearch (paramètres "offset" et "limit")

**Comment by patou** [comment]
Bon la correction que j'ai faite affiche maintenant la liste en 500ms pour 800ko.
C'est plutôt performant cela.

**Comment by patou** [comment]
> Super, attention à être sûrs que tout s'affiche (cf. question posée à Célestin dans un autre ticket tout à l'heure).

Pour cela il serais vraiment important d'avoir un deuxième environnement de test...
