### ISSUE TITLE
Filtre par nombres de claviers

### ISSUE THREAD

**Issue by patou** [inventaire-des-orgues/portail#547]
Si je veux voir les orgue avec V claviers en France et un pédalier, je doit obligatoirement cocher V et P
![image](https://user-images.githubusercontent.com/841858/129077122-1b45ea63-eb14-4433-9ee0-cab4ab275e2c.png)

Sans cocher :
![image](https://user-images.githubusercontent.com/841858/129077041-c3b9201f-6236-4399-8054-f8cd8d10707f.png)

Est-ce que c'est un comportement voulu ?

**Comment by GwilhermPoullennec** [comment]
Je ne pense pas qu'il faille alourdir encore l'interface.
- Soit opter pour une syntaxe de bon sens mais plus simple (textbox avec exemple grisé "ex : I-III/P" (qui dans ce cas sortirait tous les orgues de I à III claviers avec pédalier.
- Soit conserver le système de Célestin, mais éventuellement en plaçant la case clavier sur une autre ligne avec label explicite ("avec pédalier")

**Comment by CelestinHuet** [comment]
J'ai une préférence pour la deuxième solution. Les cases à cocher me semblent toujours plus simples à utiliser que de remplir une textbox en respectant une syntaxe particulière.

**Comment by patou** [comment]
On aurais donc sur deux lignes :
  [ ] I [ ] II [ ] III [ ] IV [ ] V
  [ ] Avec pédalier [ ] sans composition

Le VI n'existe pas en France
Le non renseigné n'est pas claire.

- Sans composition ?
- A compléter ?
- ...

**Comment by CelestinHuet** [comment]
Notre-Dame de Paris est un VI/P

**Comment by patou** [comment]
> Notre-Dame de Paris est un VI/P

Effectivement, il a 5 claviers mais 6 plan sonore qui peut ainsi être joué sur plusieurs clavier.

La philharmonie a aussi un plan sonore du même genre.
