### ISSUE TITLE
Pedal et Pedalwerk ne sont pas considérés comme pédalier 

### ISSUE THREAD

**Issue by CelestinHuet** [inventaire-des-orgues/portail#548]
Sur la carte, l'orgue de Saint-Louis-en-l'Ile de Paris apparait comme un IV et non comme un III/P.
Pareil pour l'orgue de Saint-Just de Danjoutin qui apparait comme un III et non et II/P.

**Comment by patou** [comment]
Si ces claviers sont bien considérer comme des pédaliers, mais c'est orgues n'ont pas été modifié depuis le changement que j'avais fait #475 
Et donc le resume_composition n'est pas à jour.

**Comment by patou** [comment]
Après modification de Saint Louis en l'Ile :
![image](https://user-images.githubusercontent.com/841858/129186475-07224e04-88fe-4f39-be50-bb0e15c39982.png)

**Comment by patou** [comment]
Et Saint Just en Danjoutin : 
![image](https://user-images.githubusercontent.com/841858/129186799-20e80e8f-8a82-45c2-8f4b-d391c7863fbc.png)

**Comment by patou** [comment]
@GwilhermPoullennec 
Je pense qu'il faudrait lancer sur le serveur le script :
```
python manage.py calcul_resume_clavier
```

**Comment by GwilhermPoullennec** [comment]
Ce script vient d'être lancé et est en train de tourner.
