### ISSUE TITLE
Images inaccessibles en mode édition

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/portail#559]
https://inventaire-des-orgues.fr/images/9ee8630c-c12c-423e-aada-4bcd461ebdf1/

J'ai au auparavant un 500 en voulant supprimer une image.

**Comment by GwilhermPoullennec** [comment]
Lié à la PR #558

**Comment by GwilhermPoullennec** [comment]
J'ai exécuté un petit flash back sur cette pull request en attendant...

**Comment by GwilhermPoullennec** [comment]
Je referai un test en passant les migrations.

**Comment by patou** [comment]
Tu as l'erreur qui apparait ?
Mon code ne fait pas de changement de la base donnée donc c'est étonnant.
Il est vraiment primordialement d'avoir l'environnement de test/recette et accéder au logs du serveur.

**Comment by GwilhermPoullennec** [comment]
erreur 500
Je n'ai pas creusé beaucoup plus loin...

**Comment by patou** [comment]
J'ai trouvé c'est quand il y a pas d'image, l'image principale n'existe
pas, il ne faut pas l'afficher.
