### ISSUE TITLE
[Liste] La vignette est trop petite pour certaines longues liste de facteurs

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/portail#569]
![bug_affichage orgue liste](https://user-images.githubusercontent.com/30436457/130267544-b51b4fc0-809a-4cdf-a080-b592ff39e33c.png)

Mais je ne pense pas qu'il faille agrandir la vignette.
Idée : raboter la liste des facteurs et la terminer si elle est trop longue par des pointillés.

**Comment by patou** [comment]
Sur l'exemple donné, il y a pas de soucis d'affichage même avec la longue liste des facteurs.

Le CSS qui permet d'ajouter les ... ne marche sur sur une ligne et pas en multi-ligne.
La version multi-ligne (https://css-tricks.com/almanac/properties/l/line-clamp/) est expérimental sur les navigateurs webkit (chrome, Edge Chromium, Safari) et Firefox (cela fait quand même 96% du public : 
https://caniuse.com/css-line-clamp
