### ISSUE TITLE
[images] Le bouton "Retour" est un peu confusant

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/portail#571]
Distinguer deux boutons "Retour" et "Valider"
ou bien
Le renommer

**Comment by patou** [comment]
En fait ce bouton, ne fait rien. L'upload d'une image est automatiquement ajouté.

Donc Valider n'a pas de sens.

Je propose "Terminer" ?

**Comment by GwilhermPoullennec** [comment]
OK !
