### ISSUE TITLE
Mettre à jour meilisearch

### ISSUE THREAD

**Issue by patou** [inventaire-des-orgues/portail#575]
Meilisearch 0.21 est sortie avec un nouveau moteur de recherche plus puissant : 
https://blog.meilisearch.com/whats-new-in-v0-21/

Il y a plusieurs fonctionnalités que l'on pourrait mettre en oeuvre : 
- filtre et facets.
- Phrase search (recherche d'un facteurs avec nom et prénom).
- Highlight (Afficher sur les résultats les mots cherché en gras).

@LucasBerbesson  Je sais pas comment mettre à jour le serveur pour passer sur la nouvelle version ?

La recherche Geographique est prévu pour le Q3 : https://roadmap.meilisearch.com/c/33-geo-search

**Comment by LucasBerbesson** [comment]
Ok super, je peux mettre à jour sur le serveur à une date précise si on prévoit une release qui utilise les nouvelles fonctionnalités

**Comment by LucasBerbesson** [comment]
Les "facets" sont vraiment top, à mon avis ici https://github.com/inventaire-des-orgues/portail/blob/aefa4a087ad5ddc461a495bee8f6474832b58784/orgues/templates/orgues/orgue_list.html#L21 il faudra plutôt prévoir des champs de recherche car les listes déroulantes sont vraiment très longues

**Comment by patou** [comment]
> Les "facets" sont vraiment top, à mon avis ici https://github.com/inventaire-des-orgues/portail/blob/aefa4a087ad5ddc461a495bee8f6474832b58784/orgues/templates/orgues/orgue_list.html#L21 il faudra plutôt prévoir des champs de recherche car les listes déroulantes sont vraiment très longues

Les listes sont triés par nb d'occurrences.
Et je pensais ajouter un mécanisme pour afficher x éléments et permettre d'en afficher plus. c'est ce que fait Amazon par exemple.
Et pourquoi pas un champ text pour filtrer.

Les facets région et département pourront ensuite permettre d'afficher la carte avec les regroupements fictif sur les régions où départements en fonction du zoom.

**Comment by patou** [comment]
> Ok super, je peux mettre à jour sur le serveur à une date précise si on prévoit une release qui utilise les nouvelles fonctionnalités

Il est possible de mettre à jour dès maintenant avant de merger l'utilisation des facets.

Mais il serait intéressant d'avoir l'environnement de recette (cf #555) pour pouvoir tester avant les nouvelles fonctionnalités.

**Comment by LucasBerbesson** [comment]
Je peux mettre en place un environnement de recette sur le serveur par contre je voudrais éviter d'installer 2 versions différentes de meilisearch juste pour tester

**Comment by patou** [comment]
Normalement, la dernière version reste compatible avec les anciennes libs clients (j'ai la dernière version sur mon ordinateur et je peux toujours indexer et rechercher avec la lib précedente...).
Donc on peut mettre à jour le meilisearch.
Et utiliser un autre nom d'index pour la recette (des variables d'environnements pour le nom de l'index) pour l'environnement de recette.

**Comment by GwilhermPoullennec** [comment]
Merci pour cette puissante fonctionnalité !
En revanche, cela fait énormément d'informations et le site n'est plus "responsive".

Limiter le nombre de résultats ?
Enrouler tout dans un bandeau dédié "Recherche approfondie" ?

**Comment by patou** [comment]
> Merci pour cette puissante fonctionnalité !
> En revanche, cela fait énormément d'informations et le site n'est plus "responsive".
> 
> Limiter le nombre de résultats ?
> Enrouler tout dans un bandeau dédié "Recherche approfondie" ?
> 

La PR était en draft, donc pas terminé pour avoir une fonctionnalité déployable.
Le pensait limiter la liste à x éléments avec un voir la suite pour dérouler la liste.
Ne pas afficher un item si il y a un seul élément.
Et en mode mobile, toute la liste est replié dans un sidebar.

**Comment by GwilhermPoullennec** [comment]
OK, pour aller au plus urgent, si simplement :
- tu ajoutes un "hidden" ou équivalent sur sortie petit écran
- tu limites à x entrées
ce sera super !
Merci beaucoup.

**Comment by patou** [comment]
On a maintenant la version 0.22 qui est sortis avec la possibilité de changer le trie : 
https://blog.meilisearch.com/whats-new-in-v0-22/

Ils sont bien productif ... (prochaine version, on aura la recherche geographique...)
