### ISSUE TITLE
Peaufiner ergonomie recherche facettes

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/portail#596]
![bug_voirplusfacettes](https://user-images.githubusercontent.com/30436457/134202435-62b4e094-0a2b-41ae-a875-e72b80f86833.png)

**Comment by GwilhermPoullennec** [comment]
Si on peut mettre un peu de top margin sur les "Voir plus", ce serait plus classe !

**Comment by patou** [comment]
Comme ça ? 
![image](https://user-images.githubusercontent.com/841858/134409827-e2dd7e0e-d330-4701-82de-2b29a7d06093.png)

**Comment by GwilhermPoullennec** [comment]
Parfait !
