### ISSUE TITLE
Edition tirage des jeux et transmission des notes

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/portail#6]
- En mode édition de la fiche, faire apparaître un court champ libre pour le tirage des jeux.
- En mode édition de la fiche, faire apparaître un court champ libre pour la transmission des notes.

**Comment by LucasBerbesson** [comment]
Ajouter des inputs (pas de textarea) et créer en bdd les champs tirage_commentaire, transmission_commentaire
