### ISSUE TITLE
[erreur 500] Sur le fiche de La Flèche, Saint-Thomas

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/portail#656]
Modification photos ou fichiers = erreur 500.
Ex : suppression de 72/FR-72154-FLECH-STTHOM1-K/images/orgue_illustration_enfants.jpg impossible

https://inventaire-des-orgues.fr/fichiers/suppression/22671/?csrfmiddlewaretoken=yKsGkXhEU2xcPt2C32gvK5rvF7JGODMdWn7bsePup2PLYP3tTwr4RhLobZuSxITU

Problème de chemin sur le disque ?

Les coordonniers sont toujours les plus mal chaussés ;-)

**Comment by LucasBerbesson** [comment]
C'est corrigé. C'était un pbm de permission, le fichier était en "root" sur le serveur et ducoup la plateforme n'avait plus les droits pour le modifier.   
Si tu te connectes en ssh pour déposer des fichiers, il faut ensuite lancer une commande pour redonner les droits de modification à l'outil

**Comment by GwilhermPoullennec** [comment]
Merci beaucoup !
Cela fait un bail que je n'ai pas déposé de fichiers par ssh, mais c'était la fiche cobaye à une époque.
En revanche je dois ajouter la gestion des permissions aux scripts:
1- déplacement d'une fiche
2- insertion des fiches scannées [on vient d'avoir les droits explicites pour les livres sur la Bretagne !]
