### ISSUE TITLE
drag/drop images : ajouter un fantôme

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/portail#661]

**Comment by LucasBerbesson** [comment]
C'est fait

**Comment by GwilhermPoullennec** [comment]
Joli Casper le fantôme !
Es-tu sûr que les modifications de place sont enregistrées automatiquement ?

**Comment by LucasBerbesson** [comment]
Oui, avec une petite latence d'1/2 seconde
