### ISSUE TITLE
Moteur de recherche : supprimer les articles

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/portail#664]
Quand on cherche "Le Mont Dore" on se retrouve avec tous les "Le".

**Comment by LucasBerbesson** [comment]
Il y a une option pour cela dans le moteur de recherche. 
j'ai retiré la liste suivante : 
`['Le','le', 'La','la', 'Les','les', 'du', 'et', 'de','en']`
A tester demain après la mise à jour de l'index de recherche cette nuit.

**Comment by GwilhermPoullennec** [comment]
Super !
