### ISSUE TITLE
Composition : Basse et dessus n'apparaît pas dans la fiche

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/portail#670]
Il faut que l'option, attachée à un jeu, s'affiche sous la forme :
(B+D)

**Comment by LucasBerbesson** [comment]
🙋‍♂️

**Comment by GwilhermPoullennec** [comment]
Testé OK.
Merci beaucoup !
(Si tu peux jeter un oeil sur #668...)
