### ISSUE TITLE
Ajout d'image impossible

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/portail#679]
il m'est impossible d'ajouter une photo sur la page suivante :

https://inventaire-des-orgues.fr/detail/orgue-paris-eglise-sainte-genevieve-des-grandes-carrieres-fr-75056-paris-stgene1-t/

Le téléchargement échoue systématiquement.

**Comment by LucasBerbesson** [comment]
C'est corrigé !
