### ISSUE TITLE
Erreur 500 sur lycée Pierre Rouge Montpellier

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/portail#687]
https://inventaire-des-orgues.fr/detail/orgue-montpellier-chapelle-du-lycee-prive-pierre-rouge-fr-34172-mtpel-prive_1-x/

**Comment by LucasBerbesson** [comment]
Les photos chargées étaient au format .HEIC
Je ne sais pas trop comment cela est possible, normalement la page de chargement des photos bloque tout ce qui n'est pas du .jpg ou png. En tout cas c'est ce qui posait pbm.
