### ISSUE TITLE
Le lien vers le code source en haut des pages de l'Inventaire ne fonctionne plus

### ISSUE THREAD

**Issue by CelestinHuet** [inventaire-des-orgues/portail#692]

**Comment by CelestinHuet** [comment]
Cela ne marche toujours pas : les fichiers templates/base.html et templates/footer.html ne sont pas les mêmes entre la branche main et la production

**Comment by GwilhermPoullennec** [comment]
Oui, je ne sais pas comment forcer la mise à jour de la production...

**Comment by GwilhermPoullennec** [comment]
Il fallait faire un
`git checkout .`
en local sur le serveur pour effacer des incohérences en local (deplacements.csv modifié en local)
