### ISSUE TITLE
Certificat SSL Expiré

### ISSUE THREAD

**Issue by patou** [inventaire-des-orgues/portail#699]
Le certificat SSL a expiré le 29 juillet, le site de l'inventaire des orgues n'est plus accessible :

<img width="1176" alt="image" src="https://github.com/inventaire-des-orgues/portail/assets/841858/821b5885-eb62-427f-aa84-1445ac93a41c">

**Comment by patou** [comment]
Le certificat a été régénéré, le site est maintenant disponible.

**Comment by GwilhermPoullennec** [comment]
Cf. #700
