### ISSUE TITLE
Ordre des items dans le cartouche résumé

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/portail#7]
- 3 infos générales :
    - facteur d’orgues + année de construction
    - élévation
    - état

- 6 infos techniques :
    - nombre de claviers + étendue
    - nombre de jeux
    - pédalier + étendue
    - ajouter : boîte expressive (oui ou non, information utile pour l’accompagnement d’un choeur ou d’un soliste comme du répertoire)
    - transmission
    - tirage des jeux

- 2 infos administratives :
    - propriétaire 
    - association

**Comment by LucasBerbesson** [comment]
J'ai modifié les infos sauf l'étendue des claviers qu'on a pas aujourd'hui
