### ISSUE TITLE
Issue testing a development instance - No primary key importing first organ - Or creating an organ

### ISSUE THREAD

**Issue by rvmanza-git** [inventaire-des-orgues/portail#734]
I wanted to test a local instance so I downloaded all the code from the master branch from GitHub into a local ubuntu 24.04.01 server.
I followed all the instructions in the README and with a bit of effort managed to get the server running locally.
I am able to navigate most of the site, search for organs, etc. But of course the database is empty.

When I try to import organs (e.g. "pays de la Loire"), or the example organ present in the code from GitHub I get an error about the primary key not being available.
_ValueError: 'Orgue' instance needs to have a primary key value before this relationship can be used._

Do I need some initialization code or data I am missing so the primary keys are available?

(Please excuse me if creating a ticket is not the right way to ask for this issue, I am a bit new to the platform. I don't know if there is a forum where I could have asked for this questions instead of creating this "issue" in GitHub).

**Comment by rvmanza-git** [comment]
Forgot to add that if I try to create an organ using the web interface I get a similar issue with primary keys not being available.

**Comment by rousseldenis** [comment]
> Forgot to add that if I try to create an organ using the web interface I get a similar issue with primary keys not being available.

@rvmanza-git Do you plan to run the site in your country ? 

I have the same idea. Not to fork the project should be the good path to go to. So, we need some changes here to support internationalization. See : https://github.com/inventaire-des-orgues/portail/issues/665#issuecomment-2340053564

**Comment by rvmanza-git** [comment]
> > Forgot to add that if I try to create an organ using the web interface I get a similar issue with primary keys not being available.
> 
> @rvmanza-git Do you plan to run the site in your country ?
> 
> I have the same idea. Not to fork the project should be the good path to go to. So, we need some changes here to support internationalization. See : [#665 (comment)](https://github.com/inventaire-des-orgues/portail/issues/665#issuecomment-2340053564)

Hi @rousseldenis ,

some friends in Belgium need a tool where to publish on the internet details about the pipe organs of their region. As I know a bit about IT they asked me to advice them with a tool. And I am exploring this tool which is freely available.
In the future (maybe when I retire in a long long future....) it would be nice to use the tool in my region in Spain to publish the details of the organs available in my region.

So indeed it would be great to have the tool expanded and internationalized so it can be customized to other parts of the world. A dream :)

By the way I found the reason of this issue I opened. I am using a too recent version of Django. I think I will have to recreate my local instance with the exact versions indicated in the settings file!

**Comment by rvmanza-git** [comment]
Issue cause: I am using a too modern version of django. The newest version behaves differently than the older one.
See https://forum.djangoproject.com/t/saving-in-3-2-versus-4-2/22926

I will reinstall my local instance with the exact versions given in the settings file of the project.

**Comment by rousseldenis** [comment]
> some friends in Belgium need a tool where to publish on the internet details about the pipe organs of their region. As I know a bit about IT they asked me to advice them with a tool. And I am exploring this tool which is freely available. In the future (maybe when I retire in a long long future....) it would be nice to use the tool in my region in Spain to publish the details of the organs available in my region.

@rvmanza-git Maybe we can get in touch with your friends as I live in Belgium and my original intent was to provide a country wide tool (some websites are region based) as there is nothing at that level. Do they live in walloon region ?

**Comment by rvmanza-git** [comment]
> > some friends in Belgium need a tool where to publish on the internet details about the pipe organs of their region. As I know a bit about IT they asked me to advice them with a tool. And I am exploring this tool which is freely available. In the future (maybe when I retire in a long long future....) it would be nice to use the tool in my region in Spain to publish the details of the organs available in my region.
> 
> @rvmanza-git Maybe we can get in touch with your friends as I live in Belgium and my original intent was to provide a country wide tool (some websites are region based) as there is nothing at that level. Do they live in walloon region ?

Yes, they live in Mons. I haven't used Github in the past, but if there is an option to send me a private message you can send me your e-mail address and I will put you in contact with them. They are organists.

**Comment by rousseldenis** [comment]
> > > some friends in Belgium need a tool where to publish on the internet details about the pipe organs of their region. As I know a bit about IT they asked me to advice them with a tool. And I am exploring this tool which is freely available. In the future (maybe when I retire in a long long future....) it would be nice to use the tool in my region in Spain to publish the details of the organs available in my region.
> > 
> > 
> > @rvmanza-git Maybe we can get in touch with your friends as I live in Belgium and my original intent was to provide a country wide tool (some websites are region based) as there is nothing at that level. Do they live in walloon region ?
> 
> Yes, they live in Mons. I haven't used Github in the past, but if there is an option to send me a private message you can send me your e-mail address and I will put you in contact with them. They are organists.

Never did it but on my github profile there is my X account. You can DM me.
