### ISSUE TITLE
Carte : faire façon site "Le bon coin"

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/portail#79]
- vectoriel par région/départements
- outre-mers en bas
- affichage taux de remplissage à côté de la carte : France, puis département région suivant zoom.
- sur page d'accueil

**Comment by GwilhermPoullennec** [comment]
- Si possible affichage des bulles avec nombre d'orgue par département donc.

**Comment by LucasBerbesson** [comment]
C'est fait. Reste plus qu'à ~~renseigner~~ compléter les états

**Comment by GwilhermPoullennec** [comment]
#89
