### ISSUE TITLE
Recherche sans trait d'union sur édifice, ne fonctionne pas.

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/portail#80]

**Comment by LucasBerbesson** [comment]
c'est corrigé

**Comment by GwilhermPoullennec** [comment]
Commité ?
La recherche sur "Paris" et "Sainte Elisabeth" ne semble pas fonctionner.

**Comment by LucasBerbesson** [comment]
J'avais oublié un petit truc, ça devrait mieux fonctionner

**Comment by GwilhermPoullennec** [comment]
OK pour le trait d'union, merci !
Si la casse pouvait ne pas être testée, ce serait super ("sainte élisabeth").

**Comment by LucasBerbesson** [comment]
Ce coup-ci c'est l'accent qui pose pbm, je les ai nettoyés dans la base de données mais pas dans la recherche de l'utilisateur (du coup il cherche 'élisabeth' dans 'eglise sainte elisabeth' et ne trouve pas...).
J'ai refait une passe et ajouté des [tests unitaires](https://github.com/inventaire-des-orgues/portail/blob/master/orgues/tests.py#L59), ça devrait le faire !

**Comment by GwilhermPoullennec** [comment]
Excellent.
