### ISSUE TITLE
L'index n'a pas été importé en totalité !

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/portail#81]
Il manque plusieurs instruments.
Je n'ai pas encore réessayé en épluchant les traces de l'import...

**Comment by LucasBerbesson** [comment]
Je ne sais pas trop comment gérer l'importation massive de données. 
Le mieux serait de passer exclusivement via l'API mais ça risque d'être un peu moins confortable. 
L'importation via CSV risque de poser des pbms quand on aura des données existantes sur le site ..

**Comment by LucasBerbesson** [comment]
J'ai amélioré la tache d'importation, ajouté un test unitaire dessus (basé sur `exemple_orgue-v3.json`) et mis à jour la doc.   
```
python manage.py import_data chemin/vers/exemple_orgue-v3.json --delete
```
La tache d'importation lève des erreurs pour les orgues dont un des éléments suivants est mal formaté ou n'existe pas dans la base de données : 
- designation
- proprietaire
- etat
- elevation
- tirage_jeux
- transmission_notes
- facteurs
- type d'événement
- type de clavier
- type de jeu
- accessoire

**Comment by GwilhermPoullennec** [comment]
Import réussi.
