### ISSUE TITLE
Ajouter module tqdm au requirements.txt de Pip

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/portail#82]

**Comment by LucasBerbesson** [comment]
ba il y est déjà non ? 🤔

**Comment by GwilhermPoullennec** [comment]
Ouais, peut-être juste une histoire de retour chariot terminal qui fait que Pycharm ne l'a pas pris en compte dans l'installation automatique des dépendances via l'IHM (bandeau proposé à l'ouverture du requirements.txt) ?
