### ISSUE TITLE
Page d'accueil, carte, les compteurs d'état restent à 0%

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/portail#89]

**Comment by LucasBerbesson** [comment]
Je pense que c'est à cause de l'arrondie, quand on clique sur l'Île-de-France
 on voit bien le 1%

**Comment by GwilhermPoullennec** [comment]
Cool !
Nota : ce sont les remarques de Guillaume le dessinateur que je note sous forme de tickets.

**Comment by LucasBerbesson** [comment]
ça marche :)
D'ailleurs il t'a donné l'illustration pour remplacer les vignettes par défaut ?
