### ISSUE TITLE
Etendue de chaque clavier

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/portail#9]
Information à pouvoir éditer et ajouter en tête de colonne dans le tableau de composition en mode lecture, juste en-dessous du titre du clavier.

**Comment by LucasBerbesson** [comment]
ok, c'est un champ libre ?

**Comment by GwilhermPoullennec** [comment]
Non, je te passe sous peu le JSON v2 du modèle de données

**Comment by GwilhermPoullennec** [comment]
Intervalle [note début -- note fin]
Avec note début et note fin sous la forme [A, B, C, D, E, F, G]+[1, 2, 3, 4, 5, 6, 7]
Exemples :
- "F1-G5"
- "C1-F5"

**Comment by LucasBerbesson** [comment]
Comme ça ? 
<img width="1374" alt="Capture d’écran 2020-01-24 à 18 56 18" src="https://user-images.githubusercontent.com/8393585/73093321-8dbf2e80-3ede-11ea-8341-c9567ed6b1f0.png">

**Comment by GwilhermPoullennec** [comment]
En fait il peut y avoir un dièse entre la lettre et le chiffre.

**Comment by LucasBerbesson** [comment]
Je ne me souviens plus si on gère l'étendue au niveau du clavier ou de l'orgue ?

**Comment by GwilhermPoullennec** [comment]
Clavier, car pour le coup celle d'un clavier n'est jamais celle de la pédale (qui n'a que deux octaves et demi en général) !
