### ISSUE TITLE
Re-rechanger le logo du ministère

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/portail#93]
Que le logo bas car ce n'est pas un site "officiel" mais un partenariat, donc interdiction du logo en haut à gauche

**Comment by GwilhermPoullennec** [comment]
Du coup on peut sûrement mettre le logo du bas en négatif + couleur, pour marque tout de même la présence du ministère.

**Comment by LucasBerbesson** [comment]
ok

**Comment by GwilhermPoullennec** [comment]
J'ai re-re-rechangé en mettant le logo officiel "Soutenu par"
