### ISSUE TITLE
Ajouter makemigrations au yml Action de Git

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/portail#97]

**Comment by LucasBerbesson** [comment]
La documentation officielle de Django recommande de gérer les fichiers de migration comme du code source (donc de ne pas les git-ignorer et de gérer les conflits de merge entre les différents développements locaux) ... https://docs.djangoproject.com/en/2.2/topics/migrations/

Le fait d'ajouter "makemigrations" au yml Action de Git va simplifier les développement mais risque de poser des problèmes en production... à voir

> The migration files for each app live in a “migrations” directory inside of that app, and are designed to be committed to, and distributed as part of, its codebase. You should be making them once on your development machine and then running the same migrations on your colleagues’ machines, your staging machines, and eventually your production machines.

**Comment by GwilhermPoullennec** [comment]
Ah oui tu avais dû déjà me raconter quelque chose dans ce goût-là. OK.
