### ISSUE TITLE
Frise pédagogique comment faire une photo de fiche d'orgue

### ISSUE THREAD

**Issue by GwilhermPoullennec** [inventaire-des-orgues/portail#98]
Cf. fichier zip avec les images plus bas.
Idée de Guillaume !

**Comment by GwilhermPoullennec** [comment]
Pour le titre du bandeau (concernant le choix d'une photo de profil d'orgue)
enfin de compte, il serait préférable de mettre en TITRE (H2) : De préférence dans le choix d'une photo de profil d'un orgue pour une meilleure lisibilité.
Qu'en penses-tu ? C'est peut-être moins agressif que l'autre titre. Tu as peut-être une meilleure idée de formulation ?

**Comment by GwilhermPoullennec** [comment]
[amliorationdeprsentationinventaire.zip](https://github.com/inventaire-des-orgues/portail/files/4775124/amliorationdeprsentationinventaire.zip)

**Comment by LucasBerbesson** [comment]
On a finalement ajouté un lien vers une page dédiée d'aide ici : 

![Capture d’écran 2020-07-02 à 10 39 53](https://user-images.githubusercontent.com/8393585/86336690-7be17480-bc50-11ea-8706-feec9b895b4d.png)

Et la page d'aide (qui pour l'instant ne contient qu'une seule section) : 
https://inventaire-des-orgues.fr/conseils/
